project:
  type: book
  output-dir: _book

book:
  title: "Linux-ShellScripting-Bash"
  author: "K19G"
  date: last-modified
  navbar:
    pinned: true
    right:
      - icon: github
        href: https://github.com/yourusername
      - icon: twitter
        href: https://twitter.com/yourusername

  sidebar:
    style: docked
    collapse-level: 1
  chapters:
    - index.qmd
    - part: "Intro To Shells"
      contents:
        - text: "Shell vs Terminal: Understanding the Difference"
          file: content/01-intro-to-shells/shell-vs-terminal.qmd
        - text: "Types of Shells"
          file: content/01-intro-to-shells/types-of-shells.qmd
        - text: "What is a Shell?"
          file: content/01-intro-to-shells/what-is-shell.qmd
    - part: "Shell Scripting"
      contents:
        - text: "Your First Shell Script"
          file: content/02-shell-scripting/first-script.qmd
        - text: "Script Execution Methods"
          file: content/02-shell-scripting/script-execution.qmd
        - text: "What is Shell Scripting?"
          file: content/02-shell-scripting/what-is-shell-scripting.qmd
    - part: "Bash Intro"
      contents:
        - text: "Bash Environment"
          file: content/03-bash-intro/bash-environment.qmd
        - text: "Bash Features"
          file: content/03-bash-intro/bash-features.qmd
        - text: "What is Bash?"
          file: content/03-bash-intro/what-is-bash.qmd
    - part: "Variables"
      contents:
        - text: "Variable Basics"
          file: content/04-variables/variable-basics.qmd
    - part: "Control"
      contents:
        - text: "Conditional Statements"
          file: content/06-control/conditional-statements.qmd
        - text: "Loops"
          file: content/06-control/loops.qmd
    - part: "Functions"
      contents:
        - text: "Function Basics"
          file: content/07-functions/function-basics.qmd
    - part: "Misc"
      contents:
        - text: "Misc"
          file: content/98-Misc/01-bash101.md
    - part: "Workbook"
      contents:
        - text: "Basic Bash Examples"
          file: content/99-Workbook/01-basic-examples.qmd
        - text: "Intermediate Bash Examples"
          file: content/99-Workbook/02-intermediate-examples.qmd
        - text: "Advanced Bash Examples"
          file: content/99-Workbook/03-advanced-examples.qmd
        - text: "Automation Examples"
          file: content/99-Workbook/04-automation-examples.qmd
        - text: "Utility Scripts"
          file: content/99-Workbook/05-utility-scripts.qmd

format:
  html:
    theme:
      light: [cosmo, styles/light.scss]
      dark: [darkly, styles/dark.scss]
    code-fold: true
    toc: true
    number-sections: false
    page-navigation: true

  pdf:
    documentclass: scrreprt
    classoption: ["oneside"]
    number-sections: false
    colorlinks: true
    geometry:
      - top=25mm
      - left=25mm
      - right=25mm
      - bottom=25mm

  epub:
    toc: true
    number-sections: false
