project:
  type: book
  output-dir: _book

book:
  title: "Linux-Commands"
  author: "K19G"
  date: last-modified
  navbar:
    pinned: true
    right:
      - icon: github
        href: https://github.com/yourusername
      - icon: twitter
        href: https://twitter.com/yourusername

  sidebar:
    style: docked
    collapse-level: 1
  chapters:
    - index.qmd
    - part: "Help Documentation"
      contents:
        - text: "apropos"
          file: content/00-help-documentation/apropos.md
        - text: "help"
          file: content/00-help-documentation/help.md
        - text: "info"
          file: content/00-help-documentation/info.md
        - text: "man"
          file: content/00-help-documentation/man.md
        - text: "Help and Documentation Commands"
          file: content/00-help-documentation/README.md
        - text: "whatis"
          file: content/00-help-documentation/whatis.md
    - part: "File Directory Management"
      contents:
        - text: "alias"
          file: content/01-file-directory-management/alias.md
        - text: "basename"
          file: content/01-file-directory-management/basename.md
        - text: "cat"
          file: content/01-file-directory-management/cat.md
        - text: "cd"
          file: content/01-file-directory-management/cd.md
        - text: "chmod"
          file: content/01-file-directory-management/chmod.md
        - text: "chown"
          file: content/01-file-directory-management/chown.md
        - text: "cp"
          file: content/01-file-directory-management/cp.md
        - text: "df"
          file: content/01-file-directory-management/df.md
        - text: "dirname"
          file: content/01-file-directory-management/dirname.md
        - text: "du"
          file: content/01-file-directory-management/du.md
        - text: "file"
          file: content/01-file-directory-management/file.md
        - text: "find"
          file: content/01-file-directory-management/find.md
        - text: "head"
          file: content/01-file-directory-management/head.md
        - text: "less"
          file: content/01-file-directory-management/less.md
        - text: "ln"
          file: content/01-file-directory-management/ln.md
        - text: "locate"
          file: content/01-file-directory-management/locate.md
        - text: "ls"
          file: content/01-file-directory-management/ls.md
        - text: "mkdir"
          file: content/01-file-directory-management/mkdir.md
        - text: "more"
          file: content/01-file-directory-management/more.md
        - text: "mv"
          file: content/01-file-directory-management/mv.md
        - text: "pwd"
          file: content/01-file-directory-management/pwd.md
        - text: "readlink"
          file: content/01-file-directory-management/readlink.md
        - text: "realpath"
          file: content/01-file-directory-management/realpath.md
        - text: "rm"
          file: content/01-file-directory-management/rm.md
        - text: "rmdir"
          file: content/01-file-directory-management/rmdir.md
        - text: "stat"
          file: content/01-file-directory-management/stat.md
        - text: "tail"
          file: content/01-file-directory-management/tail.md
        - text: "touch"
          file: content/01-file-directory-management/touch.md
        - text: "tree"
          file: content/01-file-directory-management/tree.md
        - text: "which"
          file: content/01-file-directory-management/which.md
    - part: "Archiving Compression"
      contents:
        - text: "bzip2"
          file: content/02-archiving-compression/bzip2.md
        - text: "gzip"
          file: content/02-archiving-compression/gzip.md
        - text: "tar"
          file: content/02-archiving-compression/tar.md
        - text: "unzip"
          file: content/02-archiving-compression/unzip.md
        - text: "xz"
          file: content/02-archiving-compression/xz.md
        - text: "zip"
          file: content/02-archiving-compression/zip.md
    - part: "System Information"
      contents:
        - text: "cal"
          file: content/03-system-information/cal.md
        - text: "date"
          file: content/03-system-information/date.md
        - text: "df"
          file: content/03-system-information/df.md
        - text: "du"
          file: content/03-system-information/du.md
        - text: "env"
          file: content/03-system-information/env.md
        - text: "free"
          file: content/03-system-information/free.md
        - text: "hostname"
          file: content/03-system-information/hostname.md
        - text: "hostnamectl"
          file: content/03-system-information/hostnamectl.md
        - text: "hwinfo"
          file: content/03-system-information/hwinfo.md
        - text: "id"
          file: content/03-system-information/id.md
        - text: "lscpu"
          file: content/03-system-information/lscpu.md
        - text: "lsmem"
          file: content/03-system-information/lsmem.md
        - text: "lsmod"
          file: content/03-system-information/lsmod.md
        - text: "lspci"
          file: content/03-system-information/lspci.md
        - text: "lsusb"
          file: content/03-system-information/lsusb.md
        - text: "uname"
          file: content/03-system-information/uname.md
        - text: "uptime"
          file: content/03-system-information/uptime.md
        - text: "w"
          file: content/03-system-information/w.md
        - text: "who"
          file: content/03-system-information/who.md
        - text: "whoami"
          file: content/03-system-information/whoami.md
    - part: "Process Management"
      contents:
        - text: "bg"
          file: content/04-process-management/bg.md
        - text: "fg"
          file: content/04-process-management/fg.md
        - text: "htop"
          file: content/04-process-management/htop.md
        - text: "jobs"
          file: content/04-process-management/jobs.md
        - text: "kill"
          file: content/04-process-management/kill.md
        - text: "killall"
          file: content/04-process-management/killall.md
        - text: "nice"
          file: content/04-process-management/nice.md
        - text: "nohup"
          file: content/04-process-management/nohup.md
        - text: "pidof"
          file: content/04-process-management/pidof.md
        - text: "ps"
          file: content/04-process-management/ps.md
        - text: "pstree"
          file: content/04-process-management/pstree.md
        - text: "renice"
          file: content/04-process-management/renice.md
        - text: "sleep"
          file: content/04-process-management/sleep.md
        - text: "timeout"
          file: content/04-process-management/timeout.md
        - text: "top"
          file: content/04-process-management/top.md
        - text: "watch"
          file: content/04-process-management/watch.md
    - part: "System Monitoring"
      contents:
        - text: "iostat"
          file: content/05-system-monitoring/iostat.md
        - text: "mpstat"
          file: content/05-system-monitoring/mpstat.md
        - text: "sar"
          file: content/05-system-monitoring/sar.md
        - text: "top"
          file: content/05-system-monitoring/top.md
        - text: "vmstat"
          file: content/05-system-monitoring/vmstat.md
    - part: "User Group Management"
      contents:
        - text: "chage"
          file: content/06-user-group-management/chage.md
        - text: "groupadd"
          file: content/06-user-group-management/groupadd.md
        - text: "groupdel"
          file: content/06-user-group-management/groupdel.md
        - text: "groupmod"
          file: content/06-user-group-management/groupmod.md
        - text: "passwd"
          file: content/06-user-group-management/passwd.md
        - text: "useradd"
          file: content/06-user-group-management/useradd.md
        - text: "userdel"
          file: content/06-user-group-management/userdel.md
        - text: "usermod"
          file: content/06-user-group-management/usermod.md
    - part: "Networking"
      contents:
        - text: "dig"
          file: content/07-networking/dig.md
        - text: "ftp"
          file: content/07-networking/ftp.md
        - text: "ifconfig"
          file: content/07-networking/ifconfig.md
        - text: "ip"
          file: content/07-networking/ip.md
        - text: "iptables"
          file: content/07-networking/iptables.md
        - text: "nc (netcat)"
          file: content/07-networking/nc.md
        - text: "netstat"
          file: content/07-networking/netstat.md
        - text: "nslookup"
          file: content/07-networking/nslookup.md
        - text: "ping"
          file: content/07-networking/ping.md
        - text: "rsync"
          file: content/07-networking/rsync.md
        - text: "scp"
          file: content/07-networking/scp.md
        - text: "ss"
          file: content/07-networking/ss.md
        - text: "ssh"
          file: content/07-networking/ssh.md
        - text: "telnet"
          file: content/07-networking/telnet.md
        - text: "traceroute"
          file: content/07-networking/traceroute.md
        - text: "wget"
          file: content/07-networking/wget.md
    - part: "Filesystem Management"
      contents:
        - text: "mount"
          file: content/08-filesystem-management/mount.md
    - part: "Scheduling"
      contents:
        - text: "anacron"
          file: content/09-scheduling/anacron.md
        - text: "at"
          file: content/09-scheduling/at.md
        - text: "cron"
          file: content/09-scheduling/cron.md
        - text: "crontab"
          file: content/09-scheduling/crontab.md
    - part: "Logging"
      contents:
        - text: "logger"
          file: content/10-logging/logger.md
        - text: "logrotate"
          file: content/10-logging/logrotate.md
    - part: "Hardware Management"
      contents:
        - text: "dmidecode"
          file: content/11-hardware-management/dmidecode.md
        - text: "hdparm"
          file: content/11-hardware-management/hdparm.md
        - text: "lshw"
          file: content/11-hardware-management/lshw.md
        - text: "lspci"
          file: content/11-hardware-management/lspci.md
    - part: "Filesystem"
      contents:
        - text: "blkid"
          file: content/13-filesystem/blkid.md
        - text: "fdisk"
          file: content/13-filesystem/fdisk.md
        - text: "fsck"
          file: content/13-filesystem/fsck.md
        - text: "lsblk"
          file: content/13-filesystem/lsblk.md
        - text: "mkfs"
          file: content/13-filesystem/mkfs.md
        - text: "mount"
          file: content/13-filesystem/mount.md
    - part: "Archive"
      contents:
        - text: "tar"
          file: content/14-archive/tar.md
    - part: "Documentation"
      contents:
        - text: "apropos"
          file: content/15-documentation/apropos.md
        - text: "info"
          file: content/15-documentation/info.md
        - text: "man"
          file: content/15-documentation/man.md
        - text: "whatis"
          file: content/15-documentation/whatis.md
    - part: "Terminal"
      contents:
        - text: "abduco"
          file: content/16-terminal/abduco.md
        - text: "byobu"
          file: content/16-terminal/byobu.md
        - text: "screen"
          file: content/16-terminal/screen.md
        - text: "tmate"
          file: content/16-terminal/tmate.md
        - text: "tmux"
          file: content/16-terminal/tmux.md
    - part: "Text Processing"
      contents:
        - text: "awk"
          file: content/17-text-processing/awk.md
        - text: "cut"
          file: content/17-text-processing/cut.md
        - text: "diff"
          file: content/17-text-processing/diff.md
        - text: "grep"
          file: content/17-text-processing/grep.md
        - text: "head"
          file: content/17-text-processing/head.md
        - text: "sed"
          file: content/17-text-processing/sed.md
        - text: "sort"
          file: content/17-text-processing/sort.md
        - text: "tail"
          file: content/17-text-processing/tail.md
        - text: "tee"
          file: content/17-text-processing/tee.md
        - text: "tr"
          file: content/17-text-processing/tr.md
        - text: "uniq"
          file: content/17-text-processing/uniq.md
        - text: "wc"
          file: content/17-text-processing/wc.md
        - text: "xargs"
          file: content/17-text-processing/xargs.md
    - part: "Network"
      contents:
        - text: "curl"
          file: content/18-network/curl.md
        - text: "netstat"
          file: content/18-network/netstat.md
        - text: "nmap"
          file: content/18-network/nmap.md
        - text: "ping"
          file: content/18-network/ping.md
        - text: "ss"
          file: content/18-network/ss.md
        - text: "tcpdump"
          file: content/18-network/tcpdump.md
        - text: "traceroute"
          file: content/18-network/traceroute.md
        - text: "wget"
          file: content/18-network/wget.md
    - part: "Process"
      contents:
        - text: "bg"
          file: content/19-process/bg.md
        - text: "fg"
          file: content/19-process/fg.md
        - text: "jobs"
          file: content/19-process/jobs.md
        - text: "kill"
          file: content/19-process/kill.md
        - text: "nice"
          file: content/19-process/nice.md
        - text: "nohup"
          file: content/19-process/nohup.md
        - text: "ps"
          file: content/19-process/ps.md
        - text: "renice"
          file: content/19-process/renice.md
        - text: "top"
          file: content/19-process/top.md
    - part: "Performance"
      contents:
        - text: "free"
          file: content/20-performance/free.md
        - text: "iostat"
          file: content/20-performance/iostat.md
        - text: "mpstat"
          file: content/20-performance/mpstat.md
        - text: "sar"
          file: content/20-performance/sar.md
        - text: "vmstat"
          file: content/20-performance/vmstat.md
    - part: "System Info"
      contents:
        - text: "hostname"
          file: content/21-system-info/hostname.md
        - text: "hostnamectl"
          file: content/21-system-info/hostnamectl.md
        - text: "lsb_release"
          file: content/21-system-info/lsb_release.md
        - text: "uname"
          file: content/21-system-info/uname.md
        - text: "uptime"
          file: content/21-system-info/uptime.md
    - part: "User Management"
      contents:
        - text: "chage"
          file: content/22-user-management/chage.md
        - text: "passwd"
          file: content/22-user-management/passwd.md
        - text: "useradd"
          file: content/22-user-management/useradd.md
        - text: "userdel"
          file: content/22-user-management/userdel.md
        - text: "usermod"
          file: content/22-user-management/usermod.md
    - part: "Package Management"
      contents:
        - text: "apt"
          file: content/23-package-management/apt.md
        - text: "dnf"
          file: content/23-package-management/dnf.md
        - text: "dpkg"
          file: content/23-package-management/dpkg.md
        - text: "rpm"
          file: content/23-package-management/rpm.md
        - text: "yum"
          file: content/23-package-management/yum.md
    - part: "System Runtime"
      contents:
        - text: "journalctl"
          file: content/24-system-runtime/journalctl.md
        - text: "reboot"
          file: content/24-system-runtime/reboot.md
        - text: "shutdown"
          file: content/24-system-runtime/shutdown.md
        - text: "systemctl"
          file: content/24-system-runtime/systemctl.md
    - part: "Scheduling"
      contents:
        - text: "crontab"
          file: content/25-scheduling/crontab.md
    - part: "Logging"
      contents:
        - text: "logger"
          file: content/26-logging/logger.md
    - part: "Printing"
      contents:
        - text: "lp"
          file: content/28-printing/lp.md
    - part: "Miscellaneous"
      contents:
        - text: "nmap"
          file: content/99-miscellaneous/01-nmap.qmd
        - text: "Nmap Command Template"
          file: content/99-miscellaneous/02-nmap-granite-llm.md
        - text: "Ubuntu Cheatsheat"
          file: content/99-miscellaneous/03-ubuntucheatsheat.md
        - text: "stat"
          file: content/99-miscellaneous/04-stat.md

format:
  html:
    theme:
      light: [cosmo, styles/light.scss]
      dark: [darkly, styles/dark.scss]
    code-fold: true
    toc: true
    number-sections: false
    page-navigation: true

  pdf:
    documentclass: scrreprt
    classoption: ["oneside"]
    number-sections: false
    colorlinks: true
    geometry:
      - top=25mm
      - left=25mm
      - right=25mm
      - bottom=25mm

  epub:
    toc: true
    number-sections: false
