project:
  type: book
  output-dir: _book

book:
  title: "Git-Github"
  author: "K19G"
  date: last-modified
  navbar:
    pinned: true
    right:
      - icon: github
        href: https://github.com/yourusername
      - icon: twitter
        href: https://twitter.com/yourusername

  sidebar:
    style: docked
    collapse-level: 1
  chapters:
    - index.qmd
    - part: "Intro"
      contents:
        - text: "Comprehensive Overview"
          file: content/00-Intro/00-intro.md
        - text: "Git Cheatsheet"
          file: content/00-Intro/01-git-cheatsheet.md
        - text: "The Evolution of Source Code Control Systems"
          file: content/00-Intro/intro1.md

format:
  html:
    theme:
      light: [cosmo, styles/light.scss]
      dark: [darkly, styles/dark.scss]
    code-fold: true
    toc: true
    number-sections: false
    page-navigation: true

  pdf:
    documentclass: scrreprt
    classoption: ["oneside"]
    number-sections: false
    colorlinks: true
    geometry:
      - top=25mm
      - left=25mm
      - right=25mm
      - bottom=25mm

  epub:
    toc: true
    number-sections: false
