<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Writing Kernel with AI - Mixture-of-Experts Kernels: Routing, Permutation, and Grouped GEMM</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../content/05-ai-written-kernels/01-deepseek-flashmla-and-deepgemm.html" rel="next">
<link href="../../content/04-modern-frontier/08-flash-decoding-split-kv.html" rel="prev">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark.min.css" rel="stylesheet" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Writing Kernel with AI</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/kanthi/books" rel="" target=""><i class="bi bi-github" role="img">
</i> 
 <span class="menu-text"></span></a>
  </li>  
</ul>
            <div class="quarto-navbar-tools">
  <a href="" class="quarto-color-scheme-toggle quarto-navigation-tool  px-1" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
  <a href="" class="quarto-reader-toggle quarto-navigation-tool px-1" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../content/04-modern-frontier/01-flashattention-from-scratch-fa1-to-fa3.html">Part IV: The Modern Frontier</a></li><li class="breadcrumb-item"><a href="../../content/04-modern-frontier/09-moe-routing-and-grouped-gemm.html"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Mixture-of-Experts Kernels: Routing, Permutation, and Grouped GEMM</span></a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Writing Kernel with AI</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false">
 <span class="menu-text">Part I: Parallelism, from the CPU up</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/01-parallelism-cpu-to-gpu/01-cpu-parallelism-simd-threads.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Parallelism on the CPU</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/01-parallelism-cpu-to-gpu/02-roofline-model-and-limits.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Roofline Lab: Predict Then Measure</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/01-parallelism-cpu-to-gpu/03-cuda-programming-model.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">The CUDA Programming Model &amp; GPU Puzzles</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/01-parallelism-cpu-to-gpu/04-memory-hierarchy-and-coalescing.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">The Memory Hierarchy in Anger: Matrix Transpose</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false">
 <span class="menu-text">Part II: The GEMM Worklog: Naive to cuBLAS</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/02-gemm-worklog/01-gemm-naive-to-tiled.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">GEMM Worklog I: Naive to Tiled</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/02-gemm-worklog/02-gemm-registers-and-warptiling.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">GEMM Worklog II: Registers &amp; Warp Tiling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/02-gemm-worklog/03-tensor-cores-and-wmma.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Tensor Cores &amp; WMMA: The Second Worklog</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false">
 <span class="menu-text">Part III: Attention &amp; Profiling</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/03-attention-and-profiling/01-profiling-and-debugging.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Profiling &amp; Debugging Like a Pro</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/03-attention-and-profiling/02-attention-and-flashattention-v1.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Attention: The Kernel That Ate the World &amp; FlashAttention v1</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Part IV: The Modern Frontier</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/04-modern-frontier/01-flashattention-from-scratch-fa1-to-fa3.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">FlashAttention from Scratch (FA1 → FA2 → FA3)</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/04-modern-frontier/02-beating-cublas-on-h100.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Beating cuBLAS on an H100</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/04-modern-frontier/03-triton-cutlass-cute-dsl.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Triton → CUTLASS → CuTe-DSL</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/04-modern-frontier/04-inference-serving-kernels.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Inference-Serving Kernels</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/04-modern-frontier/05-blackwell-and-nvfp4.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Blackwell &amp; NVFP4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/04-modern-frontier/06-flashattention-4.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Flash Attention 4</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/04-modern-frontier/07-pagedattention-kv-cache.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">PagedAttention and the KV Cache</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/04-modern-frontier/08-flash-decoding-split-kv.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Flash-Decoding: Split-KV Attention for Long-Context Decode</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/04-modern-frontier/09-moe-routing-and-grouped-gemm.html" class="sidebar-item-text sidebar-link active"><span class="chapter-title">Mixture-of-Experts Kernels: Routing, Permutation, and Grouped GEMM</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false">
 <span class="menu-text">Part V: AI-Written Kernels</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/05-ai-written-kernels/01-deepseek-flashmla-and-deepgemm.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">DeepSeek: FlashMLA &amp; DeepGEMM</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/05-ai-written-kernels/02-llm-generated-kernels-agent-profiler-loop.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">LLM-Generated Kernels: The Agent + Profiler Loop</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false">
 <span class="menu-text">Part VI: Kernel Engineering Capstone Projects</span></a>
          <a class="sidebar-item-toggle text-start collapsed" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-6" aria-expanded="false" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-6" class="collapse list-unstyled sidebar-section depth1 ">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/06-capstone-projects/01-crusoe-capstone-specifications.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Crusoe Capstone Specifications &amp; Problem Tracks</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/06-capstone-projects/02-verification-and-benchmarking.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Verification, Profiling, and Benchmarking Harness</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../content/06-capstone-projects/03-demo-day-and-portfolio.html" class="sidebar-item-text sidebar-link"><span class="chapter-title">Demo Day Presentation &amp; Portfolio</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#mixture-of-experts-kernels-routing-permutation-and-grouped-gemm" id="toc-mixture-of-experts-kernels-routing-permutation-and-grouped-gemm" class="nav-link active" data-scroll-target="#mixture-of-experts-kernels-routing-permutation-and-grouped-gemm">Mixture-of-Experts Kernels: Routing, Permutation, and Grouped GEMM</a>
  <ul class="collapse">
  <li><a href="#why-moe-is-a-kernel-problem" id="toc-why-moe-is-a-kernel-problem" class="nav-link" data-scroll-target="#why-moe-is-a-kernel-problem">1. Why MoE is a kernel problem</a></li>
  <li><a href="#mental-model-route-align-grouped-gemm-combine" id="toc-mental-model-route-align-grouped-gemm-combine" class="nav-link" data-scroll-target="#mental-model-route-align-grouped-gemm-combine">2. Mental model: route, align, grouped GEMM, combine</a></li>
  <li><a href="#ground-truth-first" id="toc-ground-truth-first" class="nav-link" data-scroll-target="#ground-truth-first">3. Ground truth first</a></li>
  <li><a href="#routing-semantics-the-bias-is-for-choosing-not-for-weighting" id="toc-routing-semantics-the-bias-is-for-choosing-not-for-weighting" class="nav-link" data-scroll-target="#routing-semantics-the-bias-is-for-choosing-not-for-weighting">4. Routing semantics: the bias is for choosing, not for weighting</a></li>
  <li><a href="#the-indirection-table-histogram-pad-scan-scatter" id="toc-the-indirection-table-histogram-pad-scan-scatter" class="nav-link" data-scroll-target="#the-indirection-table-histogram-pad-scan-scatter">5. The indirection table: histogram, pad, scan, scatter</a></li>
  <li><a href="#a-fused-grouped-gemm-in-triton" id="toc-a-fused-grouped-gemm-in-triton" class="nav-link" data-scroll-target="#a-fused-grouped-gemm-in-triton">6. A fused grouped GEMM in Triton</a></li>
  <li><a href="#compile-for-hopper-and-what-the-compiler-tells-you-about-decode" id="toc-compile-for-hopper-and-what-the-compiler-tells-you-about-decode" class="nav-link" data-scroll-target="#compile-for-hopper-and-what-the-compiler-tells-you-about-decode">7. Compile for Hopper, and what the compiler tells you about decode</a></li>
  <li><a href="#shapes-decide-everything-padding-stragglers-and-the-roofline" id="toc-shapes-decide-everything-padding-stragglers-and-the-roofline" class="nav-link" data-scroll-target="#shapes-decide-everything-padding-stragglers-and-the-roofline">8. Shapes decide everything: padding, stragglers, and the roofline</a></li>
  <li><a href="#where-this-sits-in-production" id="toc-where-this-sits-in-production" class="nav-link" data-scroll-target="#where-this-sits-in-production">9. Where this sits in production</a></li>
  <li><a href="#verification-and-benchmark-plan" id="toc-verification-and-benchmark-plan" class="nav-link" data-scroll-target="#verification-and-benchmark-plan">10. Verification and benchmark plan</a>
  <ul class="collapse">
  <li><a href="#functional" id="toc-functional" class="nav-link" data-scroll-target="#functional">Functional</a></li>
  <li><a href="#performance" id="toc-performance" class="nav-link" data-scroll-target="#performance">Performance</a></li>
  </ul></li>
  <li><a href="#prompting-an-ai-assistant-for-an-moe-kernel" id="toc-prompting-an-ai-assistant-for-an-moe-kernel" class="nav-link" data-scroll-target="#prompting-an-ai-assistant-for-an-moe-kernel">11. Prompting an AI assistant for an MoE kernel</a></li>
  <li><a href="#pitfalls" id="toc-pitfalls" class="nav-link" data-scroll-target="#pitfalls">Pitfalls</a></li>
  <li><a href="#checkpoint" id="toc-checkpoint" class="nav-link" data-scroll-target="#checkpoint">Checkpoint</a></li>
  <li><a href="#try-this" id="toc-try-this" class="nav-link" data-scroll-target="#try-this">Try this</a></li>
  <li><a href="#summary" id="toc-summary" class="nav-link" data-scroll-target="#summary">Summary</a></li>
  <li><a href="#sources-for-further-reading" id="toc-sources-for-further-reading" class="nav-link" data-scroll-target="#sources-for-further-reading">Sources (for further reading)</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title"><span class="chapter-title">Mixture-of-Experts Kernels: Routing, Permutation, and Grouped GEMM</span></h1>
</div>



<div class="quarto-title-meta">

    
  
    <div>
    <div class="quarto-title-meta-heading">Updated</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">October 7, 2026</p>
    </div>
  </div>
    
  </div>
  

</header>

<section id="mixture-of-experts-kernels-routing-permutation-and-grouped-gemm" class="level1">
<h1>Mixture-of-Experts Kernels: Routing, Permutation, and Grouped GEMM</h1>
<p>Most frontier open-weight models are now <strong>Mixture-of-Experts (MoE)</strong> models. DeepSeek-V3 and Kimi K2 have 256 and 384 routed experts per layer, Qwen3-235B-A22B and gpt-oss-120b have 128, and every token uses only 4 to 8 of them. The model holds hundreds of billions of parameters, but each token pays for only a few tens of billions. For a kernel engineer, that changes the central operation. Instead of one large GEMM per feed-forward layer, each layer runs <strong>dozens to hundreds of small GEMMs of different, data-dependent sizes</strong>, and the sizes are only known after the router has run on the GPU.</p>
<p>This chapter builds the MoE layer kernel by kernel. It writes a ground-truth reference, gets the routing semantics right (including the DeepSeek-style bias that is easy to misuse), builds the block-aligned indirection table that production kernels consume, writes a fused grouped GEMM in Triton that gathers and scatters rows itself, verifies it on a CPU with the Triton interpreter, compiles it for a Hopper GPU you do not own, and then uses shape arithmetic to explain why prefill and decode need different MoE kernels.</p>
<hr>
<section id="why-moe-is-a-kernel-problem" class="level2">
<h2 class="anchored" data-anchor-id="why-moe-is-a-kernel-problem">1. Why MoE is a kernel problem</h2>
<p>A dense SwiGLU feed-forward layer computes <span class="math inline">\(W_2\,(\mathrm{silu}(W_1x)\odot W_3x)\)</span> with one weight set. An MoE layer has <span class="math inline">\(E\)</span> such weight sets (the <strong>experts</strong>) plus a small <strong>router</strong> <span class="math inline">\(W_g\in\mathbb{R}^{E\times H}\)</span>. For each token, the router scores all experts, keeps the top <span class="math inline">\(k\)</span>, and the layer output is the weighted sum of those <span class="math inline">\(k\)</span> experts’ outputs.</p>
<table class="table">
<colgroup>
<col style="width: 21%">
<col style="width: 20%">
<col style="width: 12%">
<col style="width: 12%">
<col style="width: 25%">
<col style="width: 8%">
</colgroup>
<thead>
<tr class="header">
<th>Model (config.json)</th>
<th>Routed experts <span class="math inline">\(E\)</span></th>
<th>Active <span class="math inline">\(k\)</span></th>
<th>Hidden <span class="math inline">\(H\)</span></th>
<th>Expert intermediate <span class="math inline">\(I\)</span></th>
<th>Router</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Mixtral-8x7B</td>
<td>8</td>
<td>2</td>
<td>4096</td>
<td>14336</td>
<td>softmax, top-2</td>
</tr>
<tr class="even">
<td>gpt-oss-120b</td>
<td>128</td>
<td>4</td>
<td>2880</td>
<td>2880</td>
<td>softmax over top-4</td>
</tr>
<tr class="odd">
<td>Qwen3-235B-A22B</td>
<td>128</td>
<td>8</td>
<td>4096</td>
<td>1536</td>
<td>softmax, renormalized top-8</td>
</tr>
<tr class="even">
<td>DeepSeek-V3</td>
<td>256 (+1 shared)</td>
<td>8</td>
<td>7168</td>
<td>2048</td>
<td>sigmoid + bias, 8 groups, top-4 groups</td>
</tr>
<tr class="odd">
<td>Kimi K2</td>
<td>384 (+1 shared)</td>
<td>8</td>
<td>7168</td>
<td>2048</td>
<td>sigmoid + bias</td>
</tr>
</tbody>
</table>
<p>Three properties make this hard to run fast:</p>
<ol type="1">
<li><strong>Ragged, data-dependent sizes.</strong> Expert <span class="math inline">\(e\)</span> receives <span class="math inline">\(n_e\)</span> token rows, with <span class="math inline">\(\sum_e n_e = T\cdot k\)</span> for a batch of <span class="math inline">\(T\)</span> tokens. The <span class="math inline">\(n_e\)</span> change every step, live in GPU memory, and are often zero.</li>
<li><strong>Weights dominate bytes.</strong> One DeepSeek-V3 expert is <span class="math inline">\(3HI\approx 44\)</span> M parameters. Every active expert must stream its whole weight set from HBM, whether it serves one token or a thousand.</li>
<li><strong>Imbalance.</strong> Routers are trained to balance load <em>on average</em>. Any given batch can still send most tokens to a few hot experts, and the slowest expert sets the latency of the layer.</li>
</ol>
<p>The rest of the chapter is about turning “<span class="math inline">\(E\)</span> ragged GEMMs” into <strong>one launch</strong> that keeps the tensor cores busy when there is enough work, and keeps HBM busy when there is not.</p>
<hr>
</section>
<section id="mental-model-route-align-grouped-gemm-combine" class="level2">
<h2 class="anchored" data-anchor-id="mental-model-route-align-grouped-gemm-combine">2. Mental model: route, align, grouped GEMM, combine</h2>
<pre class="text"><code> x [T, H] ──router GEMM──► logits [T, E] ──top-k──► topk_ids, topk_w   [T, k]
                                                        │
                    moe_align: histogram ─► pad each expert to BLOCK_M ─► exclusive scan ─► scatter
                                                        ▼
                  sorted_ids  [padded rows]   (flat row r = token*k + slot, or a sentinel)
                  expert_ids  [padded rows / BLOCK_M]   (one expert per BLOCK_M-row tile)
                                                        │
 GEMM1:  rows of x gathered by sorted_ids // k,  B = W13[expert] ──► h   [T*k, 2I]  at row r
 act  :  silu(h[:, :I]) * h[:, I:]                                ──► a   [T*k, I]
 GEMM2:  rows of a gathered by sorted_ids,       B = W2[expert], × topk_w[r] ──► y [T*k, H] at row r
 combine: out[t] = Σ_slot y[t*k + slot]                           ──► out [T, H]</code></pre>
<p>There are two ways to feed the expert GEMMs:</p>
<table class="table">
<colgroup>
<col style="width: 25%">
<col style="width: 46%">
<col style="width: 28%">
</colgroup>
<thead>
<tr class="header">
<th>Design</th>
<th>Data movement</th>
<th>Used by</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td><strong>Permute, then grouped GEMM.</strong> Physically reorder token rows so each expert’s rows are contiguous, run a grouped GEMM with per-expert offsets, then un-permute.</td>
<td>Writes and reads a permuted copy of the activations (and of the outputs)</td>
<td><code>torch.nn.functional.grouped_mm</code>, CUTLASS grouped GEMM, DeepGEMM’s grouped layouts, most expert-parallel stacks (the all-to-all already permutes)</td>
</tr>
<tr class="even">
<td><strong>Gather and scatter inside the GEMM.</strong> Keep activations in token order; each tile reads its rows through an index table and writes results back to their original positions.</td>
<td>No permuted copy; indexed loads instead of contiguous ones</td>
<td>vLLM and SGLang <code>fused_moe</code> Triton kernels</td>
</tr>
</tbody>
</table>
<p>Both need the same metadata: how many rows each expert has, and where each expert’s rows start. Computing that is a <strong>histogram followed by a prefix sum (scan)</strong>, the same primitive that underlies radix sort.</p>
<hr>
</section>
<section id="ground-truth-first" class="level2">
<h2 class="anchored" data-anchor-id="ground-truth-first">3. Ground truth first</h2>
<p>Every faster version in this chapter is compared against two deliberately simple implementations: a per-expert loop, and a dense version that runs every expert on every token and masks the result. They share no indexing code, so a bug in one does not hide in the other.</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># file: moe_reference.py</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Ground truth for a top-k Mixture-of-Experts FFN layer (SwiGLU experts), in PyTorch on CPU.</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co">#   route:   logits = x @ Wg^T -&gt; softmax -&gt; top-k -&gt; renormalise the k weights</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co">#   experts: y_e(x) = W2_e (silu(W1_e x) * (W3_e x))</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co">#   combine: out(x) = sum_j w_j * y_{e_j}(x)</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Two independent implementations must agree: a per-expert loop and a dense "run every expert" version.</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>torch.manual_seed(<span class="dv">0</span>)</span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>T, H, I, E, TOP_K <span class="op">=</span> <span class="dv">64</span>, <span class="dv">64</span>, <span class="dv">96</span>, <span class="dv">8</span>, <span class="dv">2</span>          <span class="co"># tokens, hidden, expert intermediate, experts, k</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> route(x, w_gate, top_k, renormalize<span class="op">=</span><span class="va">True</span>):</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>    probs <span class="op">=</span> torch.softmax(x <span class="op">@</span> w_gate.T, dim<span class="op">=-</span><span class="dv">1</span>)               <span class="co"># [T, E], fp32</span></span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a>    w, ids <span class="op">=</span> torch.topk(probs, top_k, dim<span class="op">=-</span><span class="dv">1</span>)                 <span class="co"># [T, k] weights and expert ids</span></span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> renormalize:</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a>        w <span class="op">=</span> w <span class="op">/</span> w.<span class="bu">sum</span>(<span class="op">-</span><span class="dv">1</span>, keepdim<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> w, ids</span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> moe_loop(x, w_gate, w1, w3, w2, top_k):</span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Per-expert loop: gather the tokens routed to e, run e once, scatter-add weighted outputs."""</span></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a>    w, ids <span class="op">=</span> route(x, w_gate, top_k)</span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>    out <span class="op">=</span> torch.zeros_like(x)</span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> e <span class="kw">in</span> <span class="bu">range</span>(w1.shape[<span class="dv">0</span>]):</span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>        tok, slot <span class="op">=</span> torch.nonzero(ids <span class="op">==</span> e, as_tuple<span class="op">=</span><span class="va">True</span>)    <span class="co"># which tokens chose e, and in which slot</span></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a>        <span class="cf">if</span> tok.numel() <span class="op">==</span> <span class="dv">0</span>:</span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a>            <span class="cf">continue</span>                                          <span class="co"># an expert may receive no tokens at all</span></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>        xe <span class="op">=</span> x[tok]</span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>        ye <span class="op">=</span> (torch.nn.functional.silu(xe <span class="op">@</span> w1[e].T) <span class="op">*</span> (xe <span class="op">@</span> w3[e].T)) <span class="op">@</span> w2[e].T</span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>        out.index_add_(<span class="dv">0</span>, tok, ye <span class="op">*</span> w[tok, slot, <span class="va">None</span>])</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> out, ids</span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> moe_dense(x, w_gate, w1, w3, w2, top_k):</span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Run every expert on every token, then keep only the routed ones. E/k times the FLOPs, but obviously right."""</span></span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>    w, ids <span class="op">=</span> route(x, w_gate, top_k)</span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a>    gate <span class="op">=</span> torch.zeros(x.shape[<span class="dv">0</span>], w1.shape[<span class="dv">0</span>]).scatter(<span class="dv">1</span>, ids, w)        <span class="co"># [T, E], k nonzeros per row</span></span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a>    y_all <span class="op">=</span> torch.stack([(torch.nn.functional.silu(x <span class="op">@</span> w1[e].T) <span class="op">*</span> (x <span class="op">@</span> w3[e].T)) <span class="op">@</span> w2[e].T</span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a>                         <span class="cf">for</span> e <span class="kw">in</span> <span class="bu">range</span>(w1.shape[<span class="dv">0</span>])], dim<span class="op">=</span><span class="dv">1</span>)            <span class="co"># [T, E, H]</span></span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (gate[:, :, <span class="va">None</span>] <span class="op">*</span> y_all).<span class="bu">sum</span>(<span class="dv">1</span>)</span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> make_layer(H, I, E, seed<span class="op">=</span><span class="dv">0</span>):</span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a>    g <span class="op">=</span> torch.Generator().manual_seed(seed)</span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a>    s <span class="op">=</span> <span class="fl">1.0</span> <span class="op">/</span> H <span class="op">**</span> <span class="fl">0.5</span></span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> (torch.randn(E, H, generator<span class="op">=</span>g) <span class="op">*</span> s,               <span class="co"># router weight  [E, H]</span></span>
<span id="cb2-48"><a href="#cb2-48" aria-hidden="true" tabindex="-1"></a>            torch.randn(E, I, H, generator<span class="op">=</span>g) <span class="op">*</span> s,            <span class="co"># W1 (gate proj) [E, I, H]  nn.Linear layout</span></span>
<span id="cb2-49"><a href="#cb2-49" aria-hidden="true" tabindex="-1"></a>            torch.randn(E, I, H, generator<span class="op">=</span>g) <span class="op">*</span> s,            <span class="co"># W3 (up proj)   [E, I, H]</span></span>
<span id="cb2-50"><a href="#cb2-50" aria-hidden="true" tabindex="-1"></a>            torch.randn(E, H, I, generator<span class="op">=</span>g) <span class="op">/</span> I <span class="op">**</span> <span class="fl">0.5</span>)     <span class="co"># W2 (down proj) [E, H, I]</span></span>
<span id="cb2-51"><a href="#cb2-51" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-52"><a href="#cb2-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-53"><a href="#cb2-53" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="va">__name__</span> <span class="op">==</span> <span class="st">"__main__"</span>:</span>
<span id="cb2-54"><a href="#cb2-54" aria-hidden="true" tabindex="-1"></a>    x <span class="op">=</span> torch.randn(T, H)</span>
<span id="cb2-55"><a href="#cb2-55" aria-hidden="true" tabindex="-1"></a>    wg, w1, w3, w2 <span class="op">=</span> make_layer(H, I, E)</span>
<span id="cb2-56"><a href="#cb2-56" aria-hidden="true" tabindex="-1"></a>    out_loop, ids <span class="op">=</span> moe_loop(x, wg, w1, w3, w2, TOP_K)</span>
<span id="cb2-57"><a href="#cb2-57" aria-hidden="true" tabindex="-1"></a>    out_dense <span class="op">=</span> moe_dense(x, wg, w1, w3, w2, TOP_K)</span>
<span id="cb2-58"><a href="#cb2-58" aria-hidden="true" tabindex="-1"></a>    counts <span class="op">=</span> torch.bincount(ids.flatten(), minlength<span class="op">=</span>E)</span>
<span id="cb2-59"><a href="#cb2-59" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"tokens per expert :"</span>, counts.tolist(), <span class="st">" (sum ="</span>, <span class="bu">int</span>(counts.<span class="bu">sum</span>()), <span class="st">"= T*k)"</span>)</span>
<span id="cb2-60"><a href="#cb2-60" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"max |loop - dense|:"</span>, <span class="ss">f"</span><span class="sc">{</span>(out_loop <span class="op">-</span> out_dense)<span class="sc">.</span><span class="bu">abs</span>()<span class="sc">.</span><span class="bu">max</span>()<span class="sc">.</span>item()<span class="sc">:.2e}</span><span class="ss">"</span>)</span>
<span id="cb2-61"><a href="#cb2-61" aria-hidden="true" tabindex="-1"></a>    flops_moe <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> T <span class="op">*</span> TOP_K <span class="op">*</span> <span class="dv">3</span> <span class="op">*</span> H <span class="op">*</span> I</span>
<span id="cb2-62"><a href="#cb2-62" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"expert FLOPs: routed </span><span class="sc">{</span>flops_moe<span class="op">/</span><span class="fl">1e6</span><span class="sc">:.1f}</span><span class="ss"> MFLOP vs dense </span><span class="sc">{</span>flops_moe<span class="op">*</span>E<span class="op">/</span>TOP_K<span class="op">/</span><span class="fl">1e6</span><span class="sc">:.1f}</span><span class="ss"> MFLOP"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode" id="cb3"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python3</span> <span class="at">-m</span> venv .venv <span class="kw">&amp;&amp;</span> <span class="bu">.</span> .venv/bin/activate</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="ex">pip</span> install torch <span class="at">--index-url</span> https://download.pytorch.org/whl/cpu</span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a><span class="ex">pip</span> install triton numpy</span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> moe_reference.py</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Output (PyTorch 2.14.1 CPU):</p>
<pre class="text"><code>tokens per expert : [19, 11, 15, 15, 21, 15, 18, 14]  (sum = 128 = T*k)
max |loop - dense|: 0.00e+00
expert FLOPs: routed 4.7 MFLOP vs dense 18.9 MFLOP</code></pre>
<p>The two implementations agree to the last bit here because they run the same row-wise products on the same CPU kernels. The FLOP line is the reason MoE exists: with <span class="math inline">\(k/E = 2/8\)</span> the routed layer does a quarter of the dense work. DeepSeek-V3’s <span class="math inline">\(8/256\)</span> is <span class="math inline">\(1/32\)</span>.</p>
<p>Note the indexing contract that every later kernel keeps: the <span class="math inline">\(T\cdot k\)</span> routed copies of the tokens are numbered by a <strong>flat row</strong> <span class="math inline">\(r = t\cdot k + j\)</span> (token <span class="math inline">\(t\)</span>, slot <span class="math inline">\(j\)</span>). Expert loads are just <code>bincount</code> over the flattened <code>topk_ids</code>.</p>
<hr>
</section>
<section id="routing-semantics-the-bias-is-for-choosing-not-for-weighting" class="level2">
<h2 class="anchored" data-anchor-id="routing-semantics-the-bias-is-for-choosing-not-for-weighting">4. Routing semantics: the bias is for choosing, not for weighting</h2>
<p>Softmax-then-top-<span class="math inline">\(k\)</span> (Mixtral, Qwen3) is simple. DeepSeek-V3 and Kimi K2 use a router that kernel ports regularly get wrong:</p>
<ul>
<li>scores are <strong>sigmoid</strong> affinities, not a softmax;</li>
<li>a per-expert <strong>correction bias</strong>, adjusted during training to balance load without an auxiliary loss, is added to the scores <strong>only to select experts</strong>;</li>
<li><strong>group-limited routing:</strong> experts are split into groups (8 groups for DeepSeek-V3). Each group is scored by the sum of its top-2 biased scores, only the best <code>topk_group</code> groups (4) stay eligible, and top-<span class="math inline">\(k\)</span> is taken inside them. In deployment this bounds how many nodes a token’s experts span;</li>
<li>the gate weights come from the <strong>unbiased</strong> sigmoid scores, are renormalized over the <span class="math inline">\(k\)</span> chosen experts, and are multiplied by <code>routed_scaling_factor</code> (2.5 for DeepSeek-V3).</li>
</ul>
<div class="sourceCode" id="cb5"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="co"># file: router_grouped.py</span></span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a><span class="co"># DeepSeek-V3-style routing: sigmoid scores, a per-expert correction bias that steers SELECTION only</span></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># (auxiliary-loss-free load balancing), group-limited top-k, renormalisation and a fixed scale.</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-6"><a href="#cb5-6" aria-hidden="true" tabindex="-1"></a>torch.manual_seed(<span class="dv">0</span>)</span>
<span id="cb5-7"><a href="#cb5-7" aria-hidden="true" tabindex="-1"></a>T, E, K, N_GROUP, TOPK_GROUP, SCALE <span class="op">=</span> <span class="dv">4</span>, <span class="dv">16</span>, <span class="dv">4</span>, <span class="dv">4</span>, <span class="dv">2</span>, <span class="fl">2.5</span>   <span class="co"># small stand-ins for 256 / 8 / 8 / 4 / 2.5</span></span>
<span id="cb5-8"><a href="#cb5-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-9"><a href="#cb5-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-10"><a href="#cb5-10" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> route_grouped(logits, bias, use_bias_for_weights<span class="op">=</span><span class="va">False</span>):</span>
<span id="cb5-11"><a href="#cb5-11" aria-hidden="true" tabindex="-1"></a>    scores <span class="op">=</span> torch.sigmoid(logits)                                    <span class="co"># [T, E] affinities in (0, 1)</span></span>
<span id="cb5-12"><a href="#cb5-12" aria-hidden="true" tabindex="-1"></a>    choice <span class="op">=</span> scores <span class="op">+</span> bias                                            <span class="co"># biased scores: selection only</span></span>
<span id="cb5-13"><a href="#cb5-13" aria-hidden="true" tabindex="-1"></a>    grp <span class="op">=</span> choice.view(T, N_GROUP, <span class="op">-</span><span class="dv">1</span>).topk(<span class="dv">2</span>, dim<span class="op">=-</span><span class="dv">1</span>).values.<span class="bu">sum</span>(<span class="op">-</span><span class="dv">1</span>)  <span class="co"># group score = sum of its top-2</span></span>
<span id="cb5-14"><a href="#cb5-14" aria-hidden="true" tabindex="-1"></a>    keep_grp <span class="op">=</span> grp.topk(TOPK_GROUP, dim<span class="op">=-</span><span class="dv">1</span>).indices                   <span class="co"># keep the best TOPK_GROUP groups</span></span>
<span id="cb5-15"><a href="#cb5-15" aria-hidden="true" tabindex="-1"></a>    mask <span class="op">=</span> torch.zeros(T, N_GROUP).scatter(<span class="dv">1</span>, keep_grp, <span class="fl">1.0</span>).repeat_interleave(E <span class="op">//</span> N_GROUP, dim<span class="op">=</span><span class="dv">1</span>)</span>
<span id="cb5-16"><a href="#cb5-16" aria-hidden="true" tabindex="-1"></a>    ids <span class="op">=</span> choice.masked_fill(mask <span class="op">==</span> <span class="dv">0</span>, <span class="bu">float</span>(<span class="st">"-inf"</span>)).topk(K, dim<span class="op">=-</span><span class="dv">1</span>).indices</span>
<span id="cb5-17"><a href="#cb5-17" aria-hidden="true" tabindex="-1"></a>    w <span class="op">=</span> (choice <span class="cf">if</span> use_bias_for_weights <span class="cf">else</span> scores).gather(<span class="dv">1</span>, ids)   <span class="co"># weights from UNBIASED scores</span></span>
<span id="cb5-18"><a href="#cb5-18" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> ids, SCALE <span class="op">*</span> w <span class="op">/</span> w.<span class="bu">sum</span>(<span class="op">-</span><span class="dv">1</span>, keepdim<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb5-19"><a href="#cb5-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-20"><a href="#cb5-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-21"><a href="#cb5-21" aria-hidden="true" tabindex="-1"></a>logits <span class="op">=</span> torch.randn(T, E)</span>
<span id="cb5-22"><a href="#cb5-22" aria-hidden="true" tabindex="-1"></a>bias <span class="op">=</span> torch.zeros(E)</span>
<span id="cb5-23"><a href="#cb5-23" aria-hidden="true" tabindex="-1"></a>bias[torch.arange(E) <span class="op">%</span> <span class="dv">4</span> <span class="op">==</span> <span class="dv">0</span>] <span class="op">=</span> <span class="fl">0.5</span>          <span class="co"># the balancer has been boosting under-used experts 0,4,8,12</span></span>
<span id="cb5-24"><a href="#cb5-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-25"><a href="#cb5-25" aria-hidden="true" tabindex="-1"></a>ids0, w0 <span class="op">=</span> route_grouped(logits, torch.zeros(E))</span>
<span id="cb5-26"><a href="#cb5-26" aria-hidden="true" tabindex="-1"></a>ids1, w1 <span class="op">=</span> route_grouped(logits, bias)</span>
<span id="cb5-27"><a href="#cb5-27" aria-hidden="true" tabindex="-1"></a>ids2, w2 <span class="op">=</span> route_grouped(logits, bias, use_bias_for_weights<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb5-28"><a href="#cb5-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"no bias      ids:"</span>, ids0.tolist())</span>
<span id="cb5-29"><a href="#cb5-29" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"with bias    ids:"</span>, ids1.tolist())</span>
<span id="cb5-30"><a href="#cb5-30" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"groups used     :"</span>, (ids1 <span class="op">//</span> (E <span class="op">//</span> N_GROUP)).unique(dim<span class="op">=</span><span class="va">None</span>).tolist(), <span class="st">"of"</span>, N_GROUP,</span>
<span id="cb5-31"><a href="#cb5-31" aria-hidden="true" tabindex="-1"></a>      <span class="st">"| per token:"</span>, [<span class="bu">sorted</span>(<span class="bu">set</span>(r)) <span class="cf">for</span> r <span class="kw">in</span> (ids1 <span class="op">//</span> (E <span class="op">//</span> N_GROUP)).tolist()])</span>
<span id="cb5-32"><a href="#cb5-32" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"weights (right) :"</span>, [[<span class="bu">round</span>(v, <span class="dv">3</span>) <span class="cf">for</span> v <span class="kw">in</span> r] <span class="cf">for</span> r <span class="kw">in</span> w1.tolist()])</span>
<span id="cb5-33"><a href="#cb5-33" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"weights (bug)   :"</span>, [[<span class="bu">round</span>(v, <span class="dv">3</span>) <span class="cf">for</span> v <span class="kw">in</span> r] <span class="cf">for</span> r <span class="kw">in</span> w2.tolist()])</span>
<span id="cb5-34"><a href="#cb5-34" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"max weight error from leaking the bias:"</span>, <span class="ss">f"</span><span class="sc">{</span>(w1 <span class="op">-</span> w2)<span class="sc">.</span><span class="bu">abs</span>()<span class="sc">.</span><span class="bu">max</span>()<span class="sc">.</span>item()<span class="sc">:.3f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode" id="cb6"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> router_grouped.py</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Output:</p>
<pre class="text"><code>no bias      ids: [[13, 14, 4, 5], [7, 13, 12, 14], [13, 6, 12, 7], [11, 10, 2, 1]]
with bias    ids: [[4, 12, 13, 14], [12, 4, 7, 13], [12, 4, 13, 6], [11, 8, 0, 10]]
groups used     : [0, 1, 2, 3] of 4 | per token: [[1, 3], [1, 3], [1, 3], [0, 2]]
weights (right) : [[0.635, 0.48, 0.702, 0.683], [0.637, 0.514, 0.688, 0.661], [0.561, 0.543, 0.812, 0.585], [0.962, 0.388, 0.336, 0.815]]
weights (bug)   : [[0.798, 0.685, 0.516, 0.501], [0.785, 0.692, 0.522, 0.501], [0.742, 0.729, 0.598, 0.431], [0.688, 0.633, 0.596, 0.583]]
max weight error from leaking the bias: 0.273</code></pre>
<p>Two things to read off it. First, the bias changes <strong>which</strong> experts are chosen. The boosted experts 0, 4, 8, and 12 move into the top-<span class="math inline">\(k\)</span>, and each token uses exactly two of the four groups. Second, computing the gate weights from the biased scores changes the layer output by up to 0.27 in weight per expert. Nothing crashes and every shape is right; the model just gets measurably worse. Fused router kernels (vLLM’s <code>grouped_topk</code>, SGLang’s biased group top-k) exist to do this whole block in one launch, and their unit tests check exactly this distinction.</p>
<hr>
</section>
<section id="the-indirection-table-histogram-pad-scan-scatter" class="level2">
<h2 class="anchored" data-anchor-id="the-indirection-table-histogram-pad-scan-scatter">5. The indirection table: histogram, pad, scan, scatter</h2>
<p>A tiled GEMM wants every <code>BLOCK_M</code>-row tile to use <strong>one</strong> expert’s weights. So each expert’s run of rows is padded up to a multiple of <code>BLOCK_M</code> with a sentinel row index, and a second array records the expert that owns each tile. This is the contract of vLLM’s <code>moe_align_block_size</code>:</p>
<ul>
<li><code>sorted_ids[p]</code>: the flat row <span class="math inline">\(r\)</span> at padded position <span class="math inline">\(p\)</span>, or the sentinel <span class="math inline">\(T\cdot k\)</span> for padding;</li>
<li><code>expert_ids[p // BLOCK_M]</code>: the expert for that tile;</li>
<li>the padded total, so that tiles past the end can exit at once.</li>
</ul>
<div class="sourceCode" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># file: moe_align.py</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Build the block-aligned indirection table a fused MoE GEMM consumes (same contract as vLLM's</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a><span class="co"># moe_align_block_size): sort the T*k (token, slot) pairs by expert, pad each expert's run to a</span></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># multiple of BLOCK_M with a sentinel, and record which expert owns each BLOCK_M-row tile.</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> moe_align(topk_ids, block_m, num_experts):</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>    flat <span class="op">=</span> topk_ids.flatten().to(torch.int64)                 <span class="co"># flat row r = token * k + slot</span></span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>    n <span class="op">=</span> flat.numel()</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>    counts <span class="op">=</span> torch.bincount(flat, minlength<span class="op">=</span>num_experts)      <span class="co"># 1. histogram</span></span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>    padded <span class="op">=</span> (counts <span class="op">+</span> block_m <span class="op">-</span> <span class="dv">1</span>) <span class="op">//</span> block_m <span class="op">*</span> block_m      <span class="co"># 2. round each run up to BLOCK_M</span></span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>    starts <span class="op">=</span> torch.cumsum(padded, <span class="dv">0</span>) <span class="op">-</span> padded                 <span class="co"># 3. exclusive scan -&gt; run start</span></span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>    total <span class="op">=</span> <span class="bu">int</span>(padded.<span class="bu">sum</span>())</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a>    sorted_ids <span class="op">=</span> torch.full((total,), n, dtype<span class="op">=</span>torch.int32)   <span class="co"># sentinel n = "padding row"</span></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>    order <span class="op">=</span> torch.argsort(flat, stable<span class="op">=</span><span class="va">True</span>)                  <span class="co"># rows grouped by expert, stable</span></span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>    rank <span class="op">=</span> torch.arange(n) <span class="op">-</span> (torch.cumsum(counts, <span class="dv">0</span>) <span class="op">-</span> counts)[flat[order]]</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>    sorted_ids[starts[flat[order]] <span class="op">+</span> rank] <span class="op">=</span> order.to(torch.int32)   <span class="co"># 4. scatter into the runs</span></span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>    expert_ids <span class="op">=</span> torch.repeat_interleave(torch.arange(num_experts, dtype<span class="op">=</span>torch.int32),</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>                                         padded <span class="op">//</span> block_m)   <span class="co"># one entry per BLOCK_M tile</span></span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> sorted_ids, expert_ids, total</span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="va">__name__</span> <span class="op">==</span> <span class="st">"__main__"</span>:</span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a>    <span class="co"># The worked example from vLLM's moe_align_block_size docstring.</span></span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a>    topk_ids <span class="op">=</span> torch.tensor([[<span class="dv">2</span>, <span class="dv">3</span>, <span class="dv">4</span>], [<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">4</span>], [<span class="dv">1</span>, <span class="dv">3</span>, <span class="dv">4</span>], [<span class="dv">1</span>, <span class="dv">2</span>, <span class="dv">3</span>]])</span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a>    sorted_ids, expert_ids, total <span class="op">=</span> moe_align(topk_ids, block_m<span class="op">=</span><span class="dv">4</span>, num_experts<span class="op">=</span><span class="dv">5</span>)</span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"flat expert of each row :"</span>, topk_ids.flatten().tolist())</span>
<span id="cb8-31"><a href="#cb8-31" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"sorted_ids  :"</span>, sorted_ids.tolist())</span>
<span id="cb8-32"><a href="#cb8-32" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"expert_ids  :"</span>, expert_ids.tolist())</span>
<span id="cb8-33"><a href="#cb8-33" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="st">"rows after padding:"</span>, total, <span class="st">" useful:"</span>, topk_ids.numel(),</span>
<span id="cb8-34"><a href="#cb8-34" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f" waste: </span><span class="sc">{</span><span class="dv">1</span> <span class="op">-</span> topk_ids<span class="sc">.</span>numel() <span class="op">/</span> total<span class="sc">:.0%}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode" id="cb9"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> moe_align.py</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Output:</p>
<pre class="text"><code>flat expert of each row : [2, 3, 4, 1, 2, 4, 1, 3, 4, 1, 2, 3]
sorted_ids  : [3, 6, 9, 12, 0, 4, 10, 12, 1, 7, 11, 12, 2, 5, 8, 12]
expert_ids  : [1, 2, 3, 4]
rows after padding: 16  useful: 12  waste: 25%</code></pre>
<p>This reproduces the worked example in vLLM’s <code>moe_align_block_size</code> docstring exactly. Expert 0 receives no rows, so it gets no tile and its weights are never read. Experts 1 to 4 have 3 rows each, padded to 4, and the sentinel <code>12</code> marks the padding.</p>
<p>On a GPU, the four numbered steps are one small kernel. The histogram uses shared-memory atomics, the scan over <span class="math inline">\(E\)</span> counts runs inside one CTA (with <span class="math inline">\(E\le 384\)</span> it fits easily), and each row is scattered to <code>start[e] + rank</code>. vLLM and SGLang ship CUDA versions of this kernel because, at small batch sizes, its cost is not negligible next to the GEMMs. The <code>stable=True</code> sort is a choice made here, not a requirement. Keeping rows in token order within an expert makes the gathered loads more local and the output deterministic.</p>
<hr>
</section>
<section id="a-fused-grouped-gemm-in-triton" class="level2">
<h2 class="anchored" data-anchor-id="a-fused-grouped-gemm-in-triton">6. A fused grouped GEMM in Triton</h2>
<p>The kernel is an ordinary tiled GEMM with three changes:</p>
<ol type="1">
<li><strong>Tile to expert.</strong> Program <code>pid_m</code> reads <code>expert_ids[pid_m]</code> and offsets the weight pointer by <code>expert * stride_be</code>.</li>
<li><strong>Gathered A rows.</strong> Row indices come from <code>sorted_ids</code>. For GEMM1, the input has one row per <em>token</em>, shared by its <span class="math inline">\(k\)</span> slots, so the kernel loads row <code>r // TOP_K</code>. For GEMM2, the input already has one row per flat row, so <code>TOP_K=1</code>.</li>
<li><strong>Scattered C rows, with the router weight folded in.</strong> Results are stored at row <code>r</code>, so the output comes out in token order. GEMM2 multiplies by <code>topk_w[r]</code> in the epilogue, which leaves the combine as a plain sum over <span class="math inline">\(k\)</span>.</li>
</ol>
<p>Padding rows (<code>r &gt;= num_rows</code>) are masked on load and on store. They cost tensor-core work but no memory traffic.</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="co"># file: fused_moe_triton.py</span></span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="co"># A fused-MoE grouped GEMM in Triton: one launch computes every expert's GEMM by reading a</span></span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a><span class="co"># block-aligned indirection table (moe_align.py). Each program owns BLOCK_M rows that all belong to</span></span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a><span class="co"># ONE expert, gathers their token rows from A, multiplies by that expert's weight tile, and scatters</span></span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a><span class="co"># the result to the rows' original (token, slot) positions. No permuted copy of A is ever written.</span></span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Runs on a GPU, or on CPU for correctness work with:  TRITON_INTERPRET=1 python fused_moe_triton.py</span></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> torch.nn.functional <span class="im">as</span> F</span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> triton</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> triton.language <span class="im">as</span> tl</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> moe_align <span class="im">import</span> moe_align</span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> moe_reference <span class="im">import</span> make_layer, moe_loop, route</span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a><span class="at">@triton.jit</span></span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> moe_gemm_kernel(A, B, C, SORTED_IDS, EXPERT_IDS, TOPK_W,</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>                    num_rows, padded_rows, N, K,</span>
<span id="cb11-21"><a href="#cb11-21" aria-hidden="true" tabindex="-1"></a>                    stride_am, stride_be, stride_bn, stride_cm,</span>
<span id="cb11-22"><a href="#cb11-22" aria-hidden="true" tabindex="-1"></a>                    TOP_K: tl.constexpr, MUL_ROUTED_WEIGHT: tl.constexpr,</span>
<span id="cb11-23"><a href="#cb11-23" aria-hidden="true" tabindex="-1"></a>                    BLOCK_M: tl.constexpr, BLOCK_N: tl.constexpr, BLOCK_K: tl.constexpr):</span>
<span id="cb11-24"><a href="#cb11-24" aria-hidden="true" tabindex="-1"></a>    pid_m <span class="op">=</span> tl.program_id(<span class="dv">0</span>)</span>
<span id="cb11-25"><a href="#cb11-25" aria-hidden="true" tabindex="-1"></a>    pid_n <span class="op">=</span> tl.program_id(<span class="dv">1</span>)</span>
<span id="cb11-26"><a href="#cb11-26" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> pid_m <span class="op">*</span> BLOCK_M <span class="op">&gt;=</span> padded_rows:            <span class="co"># grid is sized for the worst case; trailing tiles idle</span></span>
<span id="cb11-27"><a href="#cb11-27" aria-hidden="true" tabindex="-1"></a>        <span class="cf">return</span></span>
<span id="cb11-28"><a href="#cb11-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-29"><a href="#cb11-29" aria-hidden="true" tabindex="-1"></a>    offs_m <span class="op">=</span> pid_m <span class="op">*</span> BLOCK_M <span class="op">+</span> tl.arange(<span class="dv">0</span>, BLOCK_M)</span>
<span id="cb11-30"><a href="#cb11-30" aria-hidden="true" tabindex="-1"></a>    rows <span class="op">=</span> tl.load(SORTED_IDS <span class="op">+</span> offs_m)           <span class="co"># flat (token*TOP_K + slot), or the sentinel num_rows</span></span>
<span id="cb11-31"><a href="#cb11-31" aria-hidden="true" tabindex="-1"></a>    row_ok <span class="op">=</span> rows <span class="op">&lt;</span> num_rows</span>
<span id="cb11-32"><a href="#cb11-32" aria-hidden="true" tabindex="-1"></a>    a_rows <span class="op">=</span> rows <span class="op">//</span> TOP_K                        <span class="co"># GEMM1: A holds one row per token, shared by k slots</span></span>
<span id="cb11-33"><a href="#cb11-33" aria-hidden="true" tabindex="-1"></a>    expert <span class="op">=</span> tl.load(EXPERT_IDS <span class="op">+</span> pid_m)          <span class="co"># every row of this tile uses the same expert</span></span>
<span id="cb11-34"><a href="#cb11-34" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-35"><a href="#cb11-35" aria-hidden="true" tabindex="-1"></a>    offs_n <span class="op">=</span> pid_n <span class="op">*</span> BLOCK_N <span class="op">+</span> tl.arange(<span class="dv">0</span>, BLOCK_N)</span>
<span id="cb11-36"><a href="#cb11-36" aria-hidden="true" tabindex="-1"></a>    offs_k <span class="op">=</span> tl.arange(<span class="dv">0</span>, BLOCK_K)</span>
<span id="cb11-37"><a href="#cb11-37" aria-hidden="true" tabindex="-1"></a>    a_ptrs <span class="op">=</span> A <span class="op">+</span> a_rows[:, <span class="va">None</span>] <span class="op">*</span> stride_am <span class="op">+</span> offs_k[<span class="va">None</span>, :]</span>
<span id="cb11-38"><a href="#cb11-38" aria-hidden="true" tabindex="-1"></a>    b_ptrs <span class="op">=</span> B <span class="op">+</span> expert <span class="op">*</span> stride_be <span class="op">+</span> offs_n[<span class="va">None</span>, :] <span class="op">*</span> stride_bn <span class="op">+</span> offs_k[:, <span class="va">None</span>]   <span class="co"># B[e] is [N, K]</span></span>
<span id="cb11-39"><a href="#cb11-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-40"><a href="#cb11-40" aria-hidden="true" tabindex="-1"></a>    acc <span class="op">=</span> tl.zeros((BLOCK_M, BLOCK_N), dtype<span class="op">=</span>tl.float32)</span>
<span id="cb11-41"><a href="#cb11-41" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> k0 <span class="kw">in</span> <span class="bu">range</span>(<span class="dv">0</span>, K, BLOCK_K):</span>
<span id="cb11-42"><a href="#cb11-42" aria-hidden="true" tabindex="-1"></a>        k_ok <span class="op">=</span> (k0 <span class="op">+</span> offs_k) <span class="op">&lt;</span> K</span>
<span id="cb11-43"><a href="#cb11-43" aria-hidden="true" tabindex="-1"></a>        a <span class="op">=</span> tl.load(a_ptrs, mask<span class="op">=</span>row_ok[:, <span class="va">None</span>] <span class="op">&amp;</span> k_ok[<span class="va">None</span>, :], other<span class="op">=</span><span class="fl">0.0</span>)</span>
<span id="cb11-44"><a href="#cb11-44" aria-hidden="true" tabindex="-1"></a>        b <span class="op">=</span> tl.load(b_ptrs, mask<span class="op">=</span>k_ok[:, <span class="va">None</span>] <span class="op">&amp;</span> (offs_n[<span class="va">None</span>, :] <span class="op">&lt;</span> N), other<span class="op">=</span><span class="fl">0.0</span>)</span>
<span id="cb11-45"><a href="#cb11-45" aria-hidden="true" tabindex="-1"></a>        acc <span class="op">+=</span> tl.dot(a, b)</span>
<span id="cb11-46"><a href="#cb11-46" aria-hidden="true" tabindex="-1"></a>        a_ptrs <span class="op">+=</span> BLOCK_K</span>
<span id="cb11-47"><a href="#cb11-47" aria-hidden="true" tabindex="-1"></a>        b_ptrs <span class="op">+=</span> BLOCK_K</span>
<span id="cb11-48"><a href="#cb11-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-49"><a href="#cb11-49" aria-hidden="true" tabindex="-1"></a>    <span class="cf">if</span> MUL_ROUTED_WEIGHT:                         <span class="co"># fold the router weight into the down projection</span></span>
<span id="cb11-50"><a href="#cb11-50" aria-hidden="true" tabindex="-1"></a>        w <span class="op">=</span> tl.load(TOPK_W <span class="op">+</span> rows, mask<span class="op">=</span>row_ok, other<span class="op">=</span><span class="fl">0.0</span>)</span>
<span id="cb11-51"><a href="#cb11-51" aria-hidden="true" tabindex="-1"></a>        acc <span class="op">=</span> acc <span class="op">*</span> w[:, <span class="va">None</span>]</span>
<span id="cb11-52"><a href="#cb11-52" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-53"><a href="#cb11-53" aria-hidden="true" tabindex="-1"></a>    c_ptrs <span class="op">=</span> C <span class="op">+</span> rows[:, <span class="va">None</span>] <span class="op">*</span> stride_cm <span class="op">+</span> offs_n[<span class="va">None</span>, :]</span>
<span id="cb11-54"><a href="#cb11-54" aria-hidden="true" tabindex="-1"></a>    tl.store(c_ptrs, acc.to(C.dtype.element_ty), mask<span class="op">=</span>row_ok[:, <span class="va">None</span>] <span class="op">&amp;</span> (offs_n[<span class="va">None</span>, :] <span class="op">&lt;</span> N))</span>
<span id="cb11-55"><a href="#cb11-55" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-56"><a href="#cb11-56" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-57"><a href="#cb11-57" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> moe_gemm(a, b, out, sorted_ids, expert_ids, padded, topk_w, top_k, mul_w,</span>
<span id="cb11-58"><a href="#cb11-58" aria-hidden="true" tabindex="-1"></a>             block_m, block_n<span class="op">=</span><span class="dv">32</span>, block_k<span class="op">=</span><span class="dv">32</span>):</span>
<span id="cb11-59"><a href="#cb11-59" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""a: [rows_a, K]; b: [E, N, K] (nn.Linear layout); out: [T*k, N] written at the flat row index."""</span></span>
<span id="cb11-60"><a href="#cb11-60" aria-hidden="true" tabindex="-1"></a>    E, N, K <span class="op">=</span> b.shape</span>
<span id="cb11-61"><a href="#cb11-61" aria-hidden="true" tabindex="-1"></a>    grid <span class="op">=</span> (expert_ids.numel(), triton.cdiv(N, block_n))</span>
<span id="cb11-62"><a href="#cb11-62" aria-hidden="true" tabindex="-1"></a>    moe_gemm_kernel[grid](a, b, out, sorted_ids, expert_ids, topk_w,</span>
<span id="cb11-63"><a href="#cb11-63" aria-hidden="true" tabindex="-1"></a>                          out.shape[<span class="dv">0</span>], padded, N, K,</span>
<span id="cb11-64"><a href="#cb11-64" aria-hidden="true" tabindex="-1"></a>                          a.stride(<span class="dv">0</span>), b.stride(<span class="dv">0</span>), b.stride(<span class="dv">1</span>), out.stride(<span class="dv">0</span>),</span>
<span id="cb11-65"><a href="#cb11-65" aria-hidden="true" tabindex="-1"></a>                          TOP_K<span class="op">=</span>top_k, MUL_ROUTED_WEIGHT<span class="op">=</span>mul_w,</span>
<span id="cb11-66"><a href="#cb11-66" aria-hidden="true" tabindex="-1"></a>                          BLOCK_M<span class="op">=</span>block_m, BLOCK_N<span class="op">=</span>block_n, BLOCK_K<span class="op">=</span>block_k)</span>
<span id="cb11-67"><a href="#cb11-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-68"><a href="#cb11-68" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-69"><a href="#cb11-69" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> fused_moe(x, w_gate, w1, w3, w2, top_k, block_m<span class="op">=</span><span class="dv">16</span>):</span>
<span id="cb11-70"><a href="#cb11-70" aria-hidden="true" tabindex="-1"></a>    T, H <span class="op">=</span> x.shape</span>
<span id="cb11-71"><a href="#cb11-71" aria-hidden="true" tabindex="-1"></a>    E, I, _ <span class="op">=</span> w1.shape</span>
<span id="cb11-72"><a href="#cb11-72" aria-hidden="true" tabindex="-1"></a>    topk_w, topk_ids <span class="op">=</span> route(x, w_gate, top_k)</span>
<span id="cb11-73"><a href="#cb11-73" aria-hidden="true" tabindex="-1"></a>    sorted_ids, expert_ids, padded <span class="op">=</span> moe_align(topk_ids, block_m, E)</span>
<span id="cb11-74"><a href="#cb11-74" aria-hidden="true" tabindex="-1"></a>    sorted_ids, expert_ids <span class="op">=</span> sorted_ids.to(x.device), expert_ids.to(x.device)</span>
<span id="cb11-75"><a href="#cb11-75" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-76"><a href="#cb11-76" aria-hidden="true" tabindex="-1"></a>    w13 <span class="op">=</span> torch.cat([w1, w3], dim<span class="op">=</span><span class="dv">1</span>).contiguous()                   <span class="co"># [E, 2I, H]: gate and up in one GEMM</span></span>
<span id="cb11-77"><a href="#cb11-77" aria-hidden="true" tabindex="-1"></a>    h <span class="op">=</span> torch.empty(T <span class="op">*</span> top_k, <span class="dv">2</span> <span class="op">*</span> I, device<span class="op">=</span>x.device, dtype<span class="op">=</span>x.dtype)</span>
<span id="cb11-78"><a href="#cb11-78" aria-hidden="true" tabindex="-1"></a>    moe_gemm(x, w13, h, sorted_ids, expert_ids, padded, topk_w, top_k, <span class="va">False</span>, block_m)</span>
<span id="cb11-79"><a href="#cb11-79" aria-hidden="true" tabindex="-1"></a>    act <span class="op">=</span> F.silu(h[:, :I]) <span class="op">*</span> h[:, I:]                               <span class="co"># [T*k, I]  (fused in production)</span></span>
<span id="cb11-80"><a href="#cb11-80" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-81"><a href="#cb11-81" aria-hidden="true" tabindex="-1"></a>    y <span class="op">=</span> torch.empty(T <span class="op">*</span> top_k, H, device<span class="op">=</span>x.device, dtype<span class="op">=</span>x.dtype)</span>
<span id="cb11-82"><a href="#cb11-82" aria-hidden="true" tabindex="-1"></a>    moe_gemm(act, w2, y, sorted_ids, expert_ids, padded, topk_w.flatten().contiguous(), <span class="dv">1</span>, <span class="va">True</span>, block_m)</span>
<span id="cb11-83"><a href="#cb11-83" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> y.view(T, top_k, H).<span class="bu">sum</span>(dim<span class="op">=</span><span class="dv">1</span>), padded                   <span class="co"># combine the k weighted slots</span></span>
<span id="cb11-84"><a href="#cb11-84" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-85"><a href="#cb11-85" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-86"><a href="#cb11-86" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> grouped_mm_moe(x, w_gate, w1, w3, w2, top_k):</span>
<span id="cb11-87"><a href="#cb11-87" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Third implementation: explicit permute -&gt; torch grouped GEMM with offsets -&gt; un-permute."""</span></span>
<span id="cb11-88"><a href="#cb11-88" aria-hidden="true" tabindex="-1"></a>    T, H <span class="op">=</span> x.shape</span>
<span id="cb11-89"><a href="#cb11-89" aria-hidden="true" tabindex="-1"></a>    E <span class="op">=</span> w1.shape[<span class="dv">0</span>]</span>
<span id="cb11-90"><a href="#cb11-90" aria-hidden="true" tabindex="-1"></a>    topk_w, topk_ids <span class="op">=</span> route(x, w_gate, top_k)</span>
<span id="cb11-91"><a href="#cb11-91" aria-hidden="true" tabindex="-1"></a>    flat <span class="op">=</span> topk_ids.flatten()</span>
<span id="cb11-92"><a href="#cb11-92" aria-hidden="true" tabindex="-1"></a>    order <span class="op">=</span> torch.argsort(flat, stable<span class="op">=</span><span class="va">True</span>)                        <span class="co"># rows grouped by expert</span></span>
<span id="cb11-93"><a href="#cb11-93" aria-hidden="true" tabindex="-1"></a>    xs <span class="op">=</span> x[order <span class="op">//</span> top_k]                                          <span class="co"># the permuted copy fused_moe avoids</span></span>
<span id="cb11-94"><a href="#cb11-94" aria-hidden="true" tabindex="-1"></a>    offs <span class="op">=</span> torch.cumsum(torch.bincount(flat, minlength<span class="op">=</span>E), <span class="dv">0</span>).to(torch.int32)</span>
<span id="cb11-95"><a href="#cb11-95" aria-hidden="true" tabindex="-1"></a>    h <span class="op">=</span> F.silu(F.grouped_mm(xs, w1.transpose(<span class="op">-</span><span class="dv">2</span>, <span class="op">-</span><span class="dv">1</span>), offs<span class="op">=</span>offs)) <span class="op">*</span> <span class="op">\</span></span>
<span id="cb11-96"><a href="#cb11-96" aria-hidden="true" tabindex="-1"></a>        F.grouped_mm(xs, w3.transpose(<span class="op">-</span><span class="dv">2</span>, <span class="op">-</span><span class="dv">1</span>), offs<span class="op">=</span>offs)</span>
<span id="cb11-97"><a href="#cb11-97" aria-hidden="true" tabindex="-1"></a>    ys <span class="op">=</span> F.grouped_mm(h, w2.transpose(<span class="op">-</span><span class="dv">2</span>, <span class="op">-</span><span class="dv">1</span>), offs<span class="op">=</span>offs) <span class="op">*</span> topk_w.flatten()[order, <span class="va">None</span>]</span>
<span id="cb11-98"><a href="#cb11-98" aria-hidden="true" tabindex="-1"></a>    out <span class="op">=</span> torch.zeros_like(x)</span>
<span id="cb11-99"><a href="#cb11-99" aria-hidden="true" tabindex="-1"></a>    out.index_add_(<span class="dv">0</span>, order <span class="op">//</span> top_k, ys)                           <span class="co"># un-permute + combine</span></span>
<span id="cb11-100"><a href="#cb11-100" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> out</span>
<span id="cb11-101"><a href="#cb11-101" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-102"><a href="#cb11-102" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-103"><a href="#cb11-103" aria-hidden="true" tabindex="-1"></a><span class="cf">if</span> <span class="va">__name__</span> <span class="op">==</span> <span class="st">"__main__"</span>:</span>
<span id="cb11-104"><a href="#cb11-104" aria-hidden="true" tabindex="-1"></a>    device <span class="op">=</span> <span class="st">"cpu"</span> <span class="cf">if</span> os.environ.get(<span class="st">"TRITON_INTERPRET"</span>) <span class="op">==</span> <span class="st">"1"</span> <span class="cf">else</span> <span class="st">"cuda"</span></span>
<span id="cb11-105"><a href="#cb11-105" aria-hidden="true" tabindex="-1"></a>    H, I <span class="op">=</span> <span class="dv">64</span>, <span class="dv">96</span></span>
<span id="cb11-106"><a href="#cb11-106" aria-hidden="true" tabindex="-1"></a>    cases <span class="op">=</span> [  <span class="co"># name, tokens, experts, top_k, router bias toward expert 0</span></span>
<span id="cb11-107"><a href="#cb11-107" aria-hidden="true" tabindex="-1"></a>        (<span class="st">"uniform E=8 k=2"</span>, <span class="dv">64</span>, <span class="dv">8</span>, <span class="dv">2</span>, <span class="fl">0.0</span>),</span>
<span id="cb11-108"><a href="#cb11-108" aria-hidden="true" tabindex="-1"></a>        (<span class="st">"skewed  E=16 k=4"</span>, <span class="dv">50</span>, <span class="dv">16</span>, <span class="dv">4</span>, <span class="fl">3.0</span>),</span>
<span id="cb11-109"><a href="#cb11-109" aria-hidden="true" tabindex="-1"></a>        (<span class="st">"decode  T=1 k=2"</span>, <span class="dv">1</span>, <span class="dv">8</span>, <span class="dv">2</span>, <span class="fl">0.0</span>),</span>
<span id="cb11-110"><a href="#cb11-110" aria-hidden="true" tabindex="-1"></a>        (<span class="st">"top-1   E=8 k=1"</span>, <span class="dv">37</span>, <span class="dv">8</span>, <span class="dv">1</span>, <span class="fl">0.0</span>),</span>
<span id="cb11-111"><a href="#cb11-111" aria-hidden="true" tabindex="-1"></a>    ]</span>
<span id="cb11-112"><a href="#cb11-112" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> name, T, E, k, bias <span class="kw">in</span> cases:</span>
<span id="cb11-113"><a href="#cb11-113" aria-hidden="true" tabindex="-1"></a>        torch.manual_seed(<span class="dv">1</span>)</span>
<span id="cb11-114"><a href="#cb11-114" aria-hidden="true" tabindex="-1"></a>        wg, w1, w3, w2 <span class="op">=</span> make_layer(H, I, E, seed<span class="op">=</span><span class="dv">2</span>)</span>
<span id="cb11-115"><a href="#cb11-115" aria-hidden="true" tabindex="-1"></a>        u <span class="op">=</span> torch.nn.functional.normalize(torch.randn(H), dim<span class="op">=</span><span class="dv">0</span>)</span>
<span id="cb11-116"><a href="#cb11-116" aria-hidden="true" tabindex="-1"></a>        wg[<span class="dv">0</span>] <span class="op">+=</span> bias <span class="op">*</span> u                                            <span class="co"># make expert 0 popular:</span></span>
<span id="cb11-117"><a href="#cb11-117" aria-hidden="true" tabindex="-1"></a>        x <span class="op">=</span> torch.randn(T, H) <span class="op">+</span> <span class="fl">1.5</span> <span class="op">*</span> u                              <span class="co"># its logit rises by ~1.5*bias</span></span>
<span id="cb11-118"><a href="#cb11-118" aria-hidden="true" tabindex="-1"></a>        ref, ids <span class="op">=</span> moe_loop(x, wg, w1, w3, w2, k)</span>
<span id="cb11-119"><a href="#cb11-119" aria-hidden="true" tabindex="-1"></a>        got, padded <span class="op">=</span> fused_moe(<span class="op">*</span>(t.to(device) <span class="cf">for</span> t <span class="kw">in</span> (x, wg, w1, w3, w2)), k)</span>
<span id="cb11-120"><a href="#cb11-120" aria-hidden="true" tabindex="-1"></a>        gmm <span class="op">=</span> grouped_mm_moe(x, wg, w1, w3, w2, k)</span>
<span id="cb11-121"><a href="#cb11-121" aria-hidden="true" tabindex="-1"></a>        counts <span class="op">=</span> torch.bincount(ids.flatten(), minlength<span class="op">=</span>E)</span>
<span id="cb11-122"><a href="#cb11-122" aria-hidden="true" tabindex="-1"></a>        <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>name<span class="sc">}</span><span class="ss">: loads=</span><span class="sc">{</span>counts<span class="sc">.</span>tolist()<span class="sc">}</span><span class="ss">  rows </span><span class="sc">{</span>T<span class="op">*</span>k<span class="sc">}</span><span class="ss"> -&gt; padded </span><span class="sc">{</span>padded<span class="sc">}</span><span class="ss">  "</span></span>
<span id="cb11-123"><a href="#cb11-123" aria-hidden="true" tabindex="-1"></a>              <span class="ss">f"|fused-ref|=</span><span class="sc">{</span>(got.cpu() <span class="op">-</span> ref)<span class="sc">.</span><span class="bu">abs</span>()<span class="sc">.</span><span class="bu">max</span>()<span class="sc">.</span>item()<span class="sc">:.1e}</span><span class="ss">  "</span></span>
<span id="cb11-124"><a href="#cb11-124" aria-hidden="true" tabindex="-1"></a>              <span class="ss">f"|grouped_mm-ref|=</span><span class="sc">{</span>(gmm <span class="op">-</span> ref)<span class="sc">.</span><span class="bu">abs</span>()<span class="sc">.</span><span class="bu">max</span>()<span class="sc">.</span>item()<span class="sc">:.1e}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode" id="cb12"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="va">TRITON_INTERPRET</span><span class="op">=</span>1 <span class="ex">python</span> fused_moe_triton.py</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Output (Triton 3.8.0, PyTorch 2.14.1 CPU, interpreter mode):</p>
<pre class="text"><code>uniform E=8 k=2: loads=[18, 8, 24, 21, 15, 12, 21, 9]  rows 128 -&gt; padded 192  |fused-ref|=1.1e-06  |grouped_mm-ref|=0.0e+00
skewed  E=16 k=4: loads=[43, 5, 20, 11, 7, 7, 12, 10, 8, 15, 7, 5, 14, 20, 7, 9]  rows 200 -&gt; padded 320  |fused-ref|=1.2e-06  |grouped_mm-ref|=0.0e+00
decode  T=1 k=2: loads=[1, 0, 0, 0, 0, 1, 0, 0]  rows 2 -&gt; padded 32  |fused-ref|=3.0e-07  |grouped_mm-ref|=0.0e+00
top-1   E=8 k=1: loads=[5, 1, 11, 7, 4, 3, 6, 0]  rows 37 -&gt; padded 112  |fused-ref|=9.5e-07  |grouped_mm-ref|=0.0e+00</code></pre>
<p>What the test matrix covers:</p>
<table class="table">
<colgroup>
<col style="width: 54%">
<col style="width: 45%">
</colgroup>
<thead>
<tr class="header">
<th>Case</th>
<th>Why</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Uniform, <span class="math inline">\(E=8\)</span>, <span class="math inline">\(k=2\)</span></td>
<td>The common case; every expert has several tiles’ worth of rows or a partial tile</td>
</tr>
<tr class="even">
<td>Skewed, <span class="math inline">\(E=16\)</span>, <span class="math inline">\(k=4\)</span></td>
<td>Expert 0 takes 43 of 50 tokens. Multi-tile experts next to experts with 5 rows</td>
</tr>
<tr class="odd">
<td>Decode, <span class="math inline">\(T=1\)</span></td>
<td>Six experts have zero rows, so they get no tiles. 2 useful rows become 32 padded rows</td>
</tr>
<tr class="even">
<td>Top-1, <span class="math inline">\(T=37\)</span></td>
<td><code>TOP_K=1</code> in GEMM1 (no row sharing). Expert 7 is empty. <span class="math inline">\(T\)</span> is not a multiple of anything</td>
</tr>
<tr class="odd">
<td>Three implementations</td>
<td>Loop, fused Triton kernel, and <code>F.grouped_mm</code> with explicit permute and un-permute</td>
</tr>
</tbody>
</table>
<p>The fused kernel matches the loop to about <span class="math inline">\(10^{-6}\)</span> in FP32: the same sums, accumulated in a different order. <code>F.grouped_mm</code> is PyTorch’s public grouped-GEMM API. Its documentation targets BF16 on SM80+ CUDA GPUs. The CPU build used here also accepted FP32 inputs, which makes it a useful third opinion while developing.</p>
<p>The interpreter executes tile semantics with NumPy. It proves the <strong>indexing</strong> is right, which is where MoE kernels break. It says nothing about speed.</p>
<hr>
</section>
<section id="compile-for-hopper-and-what-the-compiler-tells-you-about-decode" class="level2">
<h2 class="anchored" data-anchor-id="compile-for-hopper-and-what-the-compiler-tells-you-about-decode">7. Compile for Hopper, and what the compiler tells you about decode</h2>
<div class="sourceCode" id="cb14"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="co"># file: compile_check.py</span></span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Ahead-of-time compile the fused-MoE GEMM for an H100 (sm_90) on a machine with no GPU,</span></span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a><span class="co"># once per specialisation the layer launches (GEMM1: TOP_K=k, no weight; GEMM2: TOP_K=1, weight).</span></span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> triton</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> triton.backends.compiler <span class="im">import</span> GPUTarget</span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> triton.compiler <span class="im">import</span> ASTSource</span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> fused_moe_triton <span class="im">import</span> moe_gemm_kernel</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a>target <span class="op">=</span> GPUTarget(<span class="st">"cuda"</span>, <span class="dv">90</span>, <span class="dv">32</span>)</span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>sig <span class="op">=</span> {<span class="st">"A"</span>: <span class="st">"*bf16"</span>, <span class="st">"B"</span>: <span class="st">"*bf16"</span>, <span class="st">"C"</span>: <span class="st">"*bf16"</span>, <span class="st">"SORTED_IDS"</span>: <span class="st">"*i32"</span>, <span class="st">"EXPERT_IDS"</span>: <span class="st">"*i32"</span>,</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>       <span class="st">"TOPK_W"</span>: <span class="st">"*fp32"</span>, <span class="st">"num_rows"</span>: <span class="st">"i32"</span>, <span class="st">"padded_rows"</span>: <span class="st">"i32"</span>, <span class="st">"N"</span>: <span class="st">"i32"</span>, <span class="st">"K"</span>: <span class="st">"i32"</span>,</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a>       <span class="st">"stride_am"</span>: <span class="st">"i32"</span>, <span class="st">"stride_be"</span>: <span class="st">"i32"</span>, <span class="st">"stride_bn"</span>: <span class="st">"i32"</span>, <span class="st">"stride_cm"</span>: <span class="st">"i32"</span>,</span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>       <span class="st">"TOP_K"</span>: <span class="st">"constexpr"</span>, <span class="st">"MUL_ROUTED_WEIGHT"</span>: <span class="st">"constexpr"</span>,</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>       <span class="st">"BLOCK_M"</span>: <span class="st">"constexpr"</span>, <span class="st">"BLOCK_N"</span>: <span class="st">"constexpr"</span>, <span class="st">"BLOCK_K"</span>: <span class="st">"constexpr"</span>}</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> name, top_k, mul_w, bm <span class="kw">in</span> [(<span class="st">"gemm1 (gate+up)"</span>, <span class="dv">8</span>, <span class="va">False</span>, <span class="dv">64</span>), (<span class="st">"gemm2 (down)   "</span>, <span class="dv">1</span>, <span class="va">True</span>, <span class="dv">64</span>),</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a>                               (<span class="st">"gemm1 decode   "</span>, <span class="dv">8</span>, <span class="va">False</span>, <span class="dv">16</span>)]:</span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>    src <span class="op">=</span> ASTSource(fn<span class="op">=</span>moe_gemm_kernel, signature<span class="op">=</span>sig,</span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>                    constexprs<span class="op">=</span>{<span class="st">"TOP_K"</span>: top_k, <span class="st">"MUL_ROUTED_WEIGHT"</span>: mul_w,</span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>                                <span class="st">"BLOCK_M"</span>: bm, <span class="st">"BLOCK_N"</span>: <span class="dv">128</span>, <span class="st">"BLOCK_K"</span>: <span class="dv">64</span>})</span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a>    k <span class="op">=</span> triton.<span class="bu">compile</span>(src, target<span class="op">=</span>target)</span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a>    ptx <span class="op">=</span> k.asm[<span class="st">"ptx"</span>]</span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a>    <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>name<span class="sc">}</span><span class="ss"> BLOCK_M=</span><span class="sc">{</span>bm<span class="sc">:&lt;3}</span><span class="ss"> num_warps=</span><span class="sc">{</span>k<span class="sc">.</span>metadata<span class="sc">.</span>num_warps<span class="sc">}</span><span class="ss"> shared=</span><span class="sc">{</span>k<span class="sc">.</span>metadata<span class="sc">.</span>shared<span class="sc">:&gt;6}</span><span class="ss"> B  "</span></span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"mma=</span><span class="sc">{</span><span class="st">'wgmma'</span> <span class="cf">if</span> <span class="st">'wgmma'</span> <span class="kw">in</span> ptx <span class="cf">else</span> (<span class="st">'mma.sync'</span> <span class="cf">if</span> <span class="st">'mma.sync'</span> <span class="kw">in</span> ptx <span class="cf">else</span> <span class="st">'none'</span>)<span class="sc">}</span><span class="ss">  "</span></span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a>          <span class="ss">f"ptx_lines=</span><span class="sc">{</span>ptx<span class="sc">.</span>count(<span class="bu">chr</span>(<span class="dv">10</span>))<span class="sc">}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode" id="cb15"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> compile_check.py</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Output (Triton 3.8.0 on a CPU-only Linux box):</p>
<pre class="text"><code>gemm1 (gate+up) BLOCK_M=64  num_warps=4 shared= 24576 B  mma=wgmma  ptx_lines=3937
gemm2 (down)    BLOCK_M=64  num_warps=4 shared= 24576 B  mma=wgmma  ptx_lines=3936
gemm1 decode    BLOCK_M=16  num_warps=4 shared= 18432 B  mma=mma.sync  ptx_lines=2294</code></pre>
<p>All three specializations lower to <code>sm_90</code> code. The last column is the useful part. With <code>BLOCK_M=64</code>, Triton emits Hopper <strong><code>wgmma</code></strong> warpgroup MMAs. With <code>BLOCK_M=16</code>, it falls back to Ampere-style <strong><code>mma.sync</code></strong>, because <code>wgmma</code> works on tiles that are 64 rows tall per warpgroup. That is the structural problem of MoE decode in one line:</p>
<ul>
<li>At decode, an active expert typically has <strong>1 to 4 rows</strong>. A 64-row tile is more than 90% padding (section 8), and a 16-row tile cannot use the Hopper MMA path at all.</li>
<li>At those sizes the layer is bandwidth-bound anyway, so wasted MMA rows cost little. What matters is that each active expert’s weights are streamed <strong>once</strong>, at full HBM bandwidth, by enough CTAs to cover the SMs.</li>
</ul>
<p>That is why production stacks keep separate MoE kernels or configurations for small batches. Common approaches are tuned configs with small <code>BLOCK_M</code> (vLLM keys its tuned Triton configs by <span class="math inline">\(E\)</span>, <span class="math inline">\(N\)</span>, and GPU), a per-token path (vLLM skips alignment when <span class="math inline">\(T\cdot k\cdot 4\le E\)</span> and gives each routed row its own tile), <strong>swap-AB</strong> schedules that put the expert’s large <span class="math inline">\(N\)</span> dimension on the MMA’s M side, and fixed-capacity “masked” layouts that keep shapes static for CUDA Graphs. The ahead-of-time compile is cheap enough to run in the agent loop for every candidate tile shape. Grep the PTX for the instruction you expect before paying for GPU time.</p>
<hr>
</section>
<section id="shapes-decide-everything-padding-stragglers-and-the-roofline" class="level2">
<h2 class="anchored" data-anchor-id="shapes-decide-everything-padding-stragglers-and-the-roofline">8. Shapes decide everything: padding, stragglers, and the roofline</h2>
<p>One active expert in FP8 holds <span class="math inline">\(3HI\)</span> bytes of weights and does <span class="math inline">\(2\cdot n_e\cdot 3HI\)</span> FLOPs for <span class="math inline">\(n_e\)</span> rows. Its arithmetic intensity against weight bytes is simply</p>
<p><span class="math display">\[
\text{FLOP per weight byte} \approx 2\,n_e \quad(\text{FP8 weights}),\qquad \approx n_e \quad(\text{BF16 weights}).
\]</span></p>
<p>An H100 SXM’s ridge point is roughly <span class="math inline">\(1979\ \text{TFLOP/s} / 3.35\ \text{TB/s}\approx 590\)</span> FLOP/byte for dense FP8. An expert needs <strong>hundreds of rows</strong> before it becomes compute-bound.</p>
<div class="sourceCode" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># file: moe_shapes.py</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Back-of-envelope numbers for one MoE layer: tokens per expert, padding waste of a block-aligned</span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="co"># grouped GEMM, and arithmetic intensity of the expert weights (the number that decides whether</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a><span class="co"># the layer is bandwidth-bound or compute-bound).</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-7"><a href="#cb17-7" aria-hidden="true" tabindex="-1"></a>rng <span class="op">=</span> np.random.default_rng(<span class="dv">0</span>)</span>
<span id="cb17-8"><a href="#cb17-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-9"><a href="#cb17-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-10"><a href="#cb17-10" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> routed_counts(tokens, k, E, skew):</span>
<span id="cb17-11"><a href="#cb17-11" aria-hidden="true" tabindex="-1"></a>    <span class="co">"""Expert loads for `tokens` tokens choosing k distinct experts; skew=0 is uniform, &gt;0 is Zipf-like."""</span></span>
<span id="cb17-12"><a href="#cb17-12" aria-hidden="true" tabindex="-1"></a>    p <span class="op">=</span> <span class="fl">1.0</span> <span class="op">/</span> np.arange(<span class="dv">1</span>, E <span class="op">+</span> <span class="dv">1</span>) <span class="op">**</span> skew</span>
<span id="cb17-13"><a href="#cb17-13" aria-hidden="true" tabindex="-1"></a>    p <span class="op">/=</span> p.<span class="bu">sum</span>()</span>
<span id="cb17-14"><a href="#cb17-14" aria-hidden="true" tabindex="-1"></a>    counts <span class="op">=</span> np.zeros(E, dtype<span class="op">=</span>np.int64)</span>
<span id="cb17-15"><a href="#cb17-15" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> _ <span class="kw">in</span> <span class="bu">range</span>(tokens):</span>
<span id="cb17-16"><a href="#cb17-16" aria-hidden="true" tabindex="-1"></a>        counts[rng.choice(E, size<span class="op">=</span>k, replace<span class="op">=</span><span class="va">False</span>, p<span class="op">=</span>p)] <span class="op">+=</span> <span class="dv">1</span></span>
<span id="cb17-17"><a href="#cb17-17" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> counts</span>
<span id="cb17-18"><a href="#cb17-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-19"><a href="#cb17-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-20"><a href="#cb17-20" aria-hidden="true" tabindex="-1"></a><span class="kw">def</span> padded_rows(counts, block_m):</span>
<span id="cb17-21"><a href="#cb17-21" aria-hidden="true" tabindex="-1"></a>    <span class="cf">return</span> <span class="bu">int</span>(((counts <span class="op">+</span> block_m <span class="op">-</span> <span class="dv">1</span>) <span class="op">//</span> block_m <span class="op">*</span> block_m).<span class="bu">sum</span>())</span>
<span id="cb17-22"><a href="#cb17-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-23"><a href="#cb17-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb17-24"><a href="#cb17-24" aria-hidden="true" tabindex="-1"></a><span class="co"># DeepSeek-V3-like layer: hidden 7168, expert intermediate 2048, 256 routed experts, top-8.</span></span>
<span id="cb17-25"><a href="#cb17-25" aria-hidden="true" tabindex="-1"></a>H, I, E, K <span class="op">=</span> <span class="dv">7168</span>, <span class="dv">2048</span>, <span class="dv">256</span>, <span class="dv">8</span></span>
<span id="cb17-26"><a href="#cb17-26" aria-hidden="true" tabindex="-1"></a>w_bytes <span class="op">=</span> <span class="dv">3</span> <span class="op">*</span> H <span class="op">*</span> I <span class="op">*</span> <span class="dv">1</span>                      <span class="co"># one expert's W1, W3, W2 in FP8 (1 byte/param)</span></span>
<span id="cb17-27"><a href="#cb17-27" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"one expert: </span><span class="sc">{</span><span class="dv">3</span><span class="op">*</span>H<span class="op">*</span>I<span class="op">/</span><span class="fl">1e6</span><span class="sc">:.1f}</span><span class="ss"> M params = </span><span class="sc">{</span>w_bytes<span class="op">/</span><span class="dv">2</span><span class="op">**</span><span class="dv">20</span><span class="sc">:.0f}</span><span class="ss"> MiB in FP8</span><span class="ch">\n</span><span class="ss">"</span>)</span>
<span id="cb17-28"><a href="#cb17-28" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span><span class="st">'tokens'</span><span class="sc">:&gt;6}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'skew'</span><span class="sc">:&gt;4}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'tok/exp'</span><span class="sc">:&gt;7}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'active'</span><span class="sc">:&gt;6}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'max'</span><span class="sc">:&gt;5}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'BLOCK_M'</span><span class="sc">:&gt;7}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'rows'</span><span class="sc">:&gt;7}</span><span class="ss"> </span><span class="sc">{</span><span class="st">'waste'</span><span class="sc">:&gt;6}</span><span class="ss"> "</span></span>
<span id="cb17-29"><a href="#cb17-29" aria-hidden="true" tabindex="-1"></a>      <span class="ss">f"</span><span class="sc">{</span><span class="st">'FLOP/B(w)'</span><span class="sc">:&gt;9}</span><span class="ss">"</span>)</span>
<span id="cb17-30"><a href="#cb17-30" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> tokens <span class="kw">in</span> (<span class="dv">1</span>, <span class="dv">16</span>, <span class="dv">128</span>, <span class="dv">1024</span>, <span class="dv">8192</span>):</span>
<span id="cb17-31"><a href="#cb17-31" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> skew <span class="kw">in</span> (<span class="fl">0.0</span>, <span class="fl">1.0</span>):</span>
<span id="cb17-32"><a href="#cb17-32" aria-hidden="true" tabindex="-1"></a>        counts <span class="op">=</span> routed_counts(tokens, K, E, skew)</span>
<span id="cb17-33"><a href="#cb17-33" aria-hidden="true" tabindex="-1"></a>        active <span class="op">=</span> <span class="bu">int</span>((counts <span class="op">&gt;</span> <span class="dv">0</span>).<span class="bu">sum</span>())</span>
<span id="cb17-34"><a href="#cb17-34" aria-hidden="true" tabindex="-1"></a>        <span class="cf">for</span> block_m <span class="kw">in</span> (<span class="dv">16</span>, <span class="dv">64</span>):</span>
<span id="cb17-35"><a href="#cb17-35" aria-hidden="true" tabindex="-1"></a>            rows <span class="op">=</span> padded_rows(counts, block_m)</span>
<span id="cb17-36"><a href="#cb17-36" aria-hidden="true" tabindex="-1"></a>            useful <span class="op">=</span> tokens <span class="op">*</span> K</span>
<span id="cb17-37"><a href="#cb17-37" aria-hidden="true" tabindex="-1"></a>            <span class="co"># FLOPs actually needed vs bytes of expert weights that must be streamed (active experts only)</span></span>
<span id="cb17-38"><a href="#cb17-38" aria-hidden="true" tabindex="-1"></a>            ai <span class="op">=</span> <span class="dv">2</span> <span class="op">*</span> useful <span class="op">*</span> <span class="dv">3</span> <span class="op">*</span> H <span class="op">*</span> I <span class="op">/</span> (active <span class="op">*</span> w_bytes)</span>
<span id="cb17-39"><a href="#cb17-39" aria-hidden="true" tabindex="-1"></a>            <span class="bu">print</span>(<span class="ss">f"</span><span class="sc">{</span>tokens<span class="sc">:&gt;6}</span><span class="ss"> </span><span class="sc">{</span>skew<span class="sc">:&gt;4}</span><span class="ss"> </span><span class="sc">{</span>useful<span class="op">/</span>E<span class="sc">:&gt;7.2f}</span><span class="ss"> </span><span class="sc">{</span>active<span class="sc">:&gt;6}</span><span class="ss"> </span><span class="sc">{</span><span class="bu">int</span>(counts.<span class="bu">max</span>())<span class="sc">:&gt;5}</span><span class="ss"> </span><span class="sc">{</span>block_m<span class="sc">:&gt;7}</span><span class="ss"> </span><span class="sc">{</span>rows<span class="sc">:&gt;7}</span><span class="ss"> "</span></span>
<span id="cb17-40"><a href="#cb17-40" aria-hidden="true" tabindex="-1"></a>                  <span class="ss">f"</span><span class="sc">{</span><span class="dv">1</span><span class="op">-</span>useful<span class="op">/</span>rows<span class="sc">:&gt;6.0%}</span><span class="ss"> </span><span class="sc">{</span>ai<span class="sc">:&gt;9.1f}</span><span class="ss">"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="sourceCode" id="cb18"><pre class="sourceCode bash code-with-copy"><code class="sourceCode bash"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="ex">python</span> moe_shapes.py</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Output:</p>
<pre class="text"><code>one expert: 44.0 M params = 42 MiB in FP8

tokens skew tok/exp active   max BLOCK_M    rows  waste FLOP/B(w)
     1  0.0    0.03      8     1      16     128    94%       2.0
     1  0.0    0.03      8     1      64     512    98%       2.0
     1  1.0    0.03      8     1      16     128    94%       2.0
     1  1.0    0.03      8     1      64     512    98%       2.0
    16  0.0    0.50    103     4      16    1648    92%       2.5
    16  0.0    0.50    103     4      64    6592    98%       2.5
    16  1.0    0.50     80    13      16    1280    90%       3.2
    16  1.0    0.50     80    13      64    5120    98%       3.2
   128  0.0    4.00    252    11      16    4032    75%       8.1
   128  0.0    4.00    252    11      64   16128    94%       8.1
   128  1.0    4.00    205   110      16    3632    72%      10.0
   128  1.0    4.00    205   110      64   13248    92%      10.0
  1024  0.0   32.00    256    47      16   10032    18%      64.0
  1024  0.0   32.00    256    47      64   16384    50%      64.0
  1024  1.0   32.00    256   774      16   10176    19%      64.0
  1024  1.0   32.00    256   774      64   20352    60%      64.0
  8192  0.0  256.00    256   308      16   67424     3%     512.0
  8192  0.0  256.00    256   308      64   73472    11%     512.0
  8192  1.0  256.00    256  6455      16   67504     3%     512.0
  8192  1.0  256.00    256  6455      64   73024    10%     512.0</code></pre>
<p>Reading the table, row by row:</p>
<ul>
<li><strong>1 to 16 tokens (decode):</strong> 8 to 103 experts are active, each with about one row. Intensity is 2 to 3 FLOP/byte, deep in bandwidth-bound territory. The padding “waste” of 90–98% is irrelevant: those MMA rows are free while the kernel waits on HBM. The real cost is <span class="math inline">\(\text{active}\times 42\)</span> MiB of weights per layer. Below about 128 tokens, each extra token can wake experts that were idle, so per-token cost falls more slowly than in a dense model. Once nearly every expert is active, extra decode tokens add <strong>no weight bytes</strong> at all, and batching becomes almost free until the ridge.</li>
<li><strong>1024 tokens:</strong> every expert is active, with 32 rows on average. Padding to 64 now wastes half the tensor-core work, so <code>BLOCK_M=16</code> or 32 is better, and still bandwidth-bound at 64 FLOP/byte.</li>
<li><strong>8192 tokens (prefill):</strong> 256 rows per expert reach the ridge, and padding waste drops to 3–11%. This is where <code>wgmma</code>-sized tiles, TMA, and warp specialization pay off, as for any large GEMM.</li>
<li><strong>Skew (<code>skew=1.0</code>):</strong> the hottest expert takes 774 of 1024 and 6455 of 8192 routed rows, so one expert holds most of the batch. A grid with one tile per <code>BLOCK_M</code> rows still runs, but the hot expert’s tiles form a long tail if tiles are scheduled expert by expert. Persistent kernels that hand out tiles from a global queue, and the load-balancing router from section 4, both exist because of this column.</li>
</ul>
<p>For expert parallelism across GPUs, the same arithmetic applies per GPU, with <span class="math inline">\(E\)</span> replaced by the local expert count and <span class="math inline">\(T\)</span> by the tokens the all-to-all delivers to that GPU.</p>
<hr>
</section>
<section id="where-this-sits-in-production" class="level2">
<h2 class="anchored" data-anchor-id="where-this-sits-in-production">9. Where this sits in production</h2>
<table class="table">
<colgroup>
<col style="width: 64%">
<col style="width: 35%">
</colgroup>
<thead>
<tr class="header">
<th>Component</th>
<th>Role</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>vLLM / SGLang <code>fused_moe</code> (Triton)</td>
<td>The gather/scatter design of section 6: <code>moe_align_block_size</code>, a <code>fused_moe_kernel</code> with FP8/INT8/INT4 weight variants, tuned configs per <span class="math inline">\((E, N, \text{GPU})\)</span>, and fused <code>silu_and_mul</code> and <code>moe_sum</code> kernels</td>
</tr>
<tr class="even">
<td><code>torch.nn.functional.grouped_mm</code></td>
<td>Public PyTorch grouped GEMM over 2-D/3-D operands with <code>offs</code>. Used for MoE training in torchtitan</td>
</tr>
<tr class="odd">
<td>CUTLASS grouped GEMM</td>
<td>Many problem sizes in one persistent launch. Problem shapes and pointer arrays can live on the device</td>
</tr>
<tr class="even">
<td>DeepGEMM grouped GEMMs</td>
<td>FP8 “m-grouped” kernels with a <strong>contiguous</strong> layout (each expert’s rows padded to the M-block alignment, for prefill and training) and a <strong>masked</strong> layout (fixed capacity per expert plus a valid-row count, for CUDA-Graph decode)</td>
</tr>
<tr class="odd">
<td>Triton grouped GEMM tutorial</td>
<td>A persistent Triton kernel that walks a device-side list of GEMM problems</td>
</tr>
<tr class="even">
<td>MegaBlocks</td>
<td>“Dropless” MoE as block-sparse GEMMs. It removed the capacity-factor token dropping of earlier MoE systems</td>
</tr>
<tr class="odd">
<td>DeepEP</td>
<td>Expert-parallel all-to-all <strong>dispatch</strong> and <strong>combine</strong>. High-throughput kernels for prefill and training, and low-latency RDMA kernels for decode</td>
</tr>
</tbody>
</table>
<p>The capacity-factor approach deserves a sentence because generated code still produces it: early MoE systems gave every expert a fixed number of slots and <strong>dropped</strong> tokens that overflowed. That gives static shapes, but it silently changes the model’s output under load. Modern inference stacks are dropless: every routed row is computed.</p>
<hr>
</section>
<section id="verification-and-benchmark-plan" class="level2">
<h2 class="anchored" data-anchor-id="verification-and-benchmark-plan">10. Verification and benchmark plan</h2>
<section id="functional" class="level3">
<h3 class="anchored" data-anchor-id="functional">Functional</h3>
<table class="table">
<colgroup>
<col style="width: 43%">
<col style="width: 56%">
</colgroup>
<thead>
<tr class="header">
<th>Check</th>
<th>Catches</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Loop vs dense vs fused vs grouped-GEMM agree</td>
<td>Index bugs in any one path</td>
</tr>
<tr class="even">
<td>Experts with 0 rows, 1 row, <code>BLOCK_M−1</code>, <code>BLOCK_M</code>, <code>BLOCK_M+1</code> rows</td>
<td>Tile-boundary and empty-expert bugs (reading weights of an expert with no tile)</td>
</tr>
<tr class="odd">
<td><span class="math inline">\(T=1\)</span> and <span class="math inline">\(T\cdot k &lt; E\)</span></td>
<td>The decode path, and any per-token fallback</td>
</tr>
<tr class="even">
<td>One expert receives every token</td>
<td>Grid sizing, the worst-case padded length, stragglers</td>
</tr>
<tr class="odd">
<td>Router: biased selection, unbiased weights, renormalization, scale factor</td>
<td>Silent quality bugs (section 4)</td>
</tr>
<tr class="even">
<td>Sentinel rows never written; output rows written exactly once per slot</td>
<td>Races and out-of-bounds stores (run <code>compute-sanitizer</code> on a GPU)</td>
</tr>
<tr class="odd">
<td>BF16/FP8 inputs vs FP32 reference with tolerances</td>
<td>Accumulating in low precision; FP8 scale handling</td>
</tr>
</tbody>
</table>
</section>
<section id="performance" class="level3">
<h3 class="anchored" data-anchor-id="performance">Performance</h3>
<table class="table">
<colgroup>
<col style="width: 50%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Metric</th>
<th>Target</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Decode: achieved bandwidth = active-expert weight bytes / layer time</td>
<td>Approaches HBM peak</td>
</tr>
<tr class="even">
<td>Prefill: achieved TFLOP/s on useful rows only (exclude padding)</td>
<td>Approaches a dense GEMM of the same total size</td>
</tr>
<tr class="odd">
<td>Alignment + router + combine share of layer time</td>
<td>Small at prefill. Watch it at decode, where it can rival the GEMMs</td>
</tr>
<tr class="even">
<td>Sweep over <span class="math inline">\(T\)</span> and routing skew</td>
<td>No cliff where the tile config changes</td>
</tr>
</tbody>
</table>
<p>Benchmark with <strong>real router outputs</strong> captured from the model on real prompts, not <code>randint</code> expert IDs. Uniform random routing hides the straggler problem that real traffic creates.</p>
<hr>
</section>
</section>
<section id="prompting-an-ai-assistant-for-an-moe-kernel" class="level2">
<h2 class="anchored" data-anchor-id="prompting-an-ai-assistant-for-an-moe-kernel">11. Prompting an AI assistant for an MoE kernel</h2>
<p>Generated MoE code tends to loop over experts in Python or to assume uniform loads. State the contract:</p>
<ol type="1">
<li><strong>Shapes and layout:</strong> <code>x [T, H]</code>, <code>w13 [E, 2I, H]</code> and <code>w2 [E, H, I]</code> in <code>nn.Linear</code> layout, <code>topk_ids/topk_w [T, k]</code>, flat row <span class="math inline">\(r = t\cdot k + j\)</span>.</li>
<li><strong>Metadata:</strong> produce <code>sorted_ids</code>, <code>expert_ids</code>, and the padded count with a sentinel. Empty experts get no tiles.</li>
<li><strong>Kernel:</strong> one launch per GEMM, tile-to-expert mapping, gathered A rows (<code>r // k</code> for GEMM1), scattered C rows, router weight in the GEMM2 epilogue, FP32 accumulation.</li>
<li><strong>Router semantics</strong> if DeepSeek-style: sigmoid, bias for selection only, group-limited top-k, renormalize, scale.</li>
<li><strong>Tests first:</strong> interpreter-mode tests against a loop <em>and</em> a dense reference across the cases in section 10, plus an AOT compile for the target with a check that the expected MMA instruction appears.</li>
<li><strong>Metric:</strong> GB/s of weights at decode, useful TFLOP/s at prefill.</li>
</ol>
<hr>
</section>
<section id="pitfalls" class="level2">
<h2 class="anchored" data-anchor-id="pitfalls">Pitfalls</h2>
<table class="table">
<colgroup>
<col style="width: 52%">
<col style="width: 47%">
</colgroup>
<thead>
<tr class="header">
<th>Pitfall</th>
<th>Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Python loop over experts</td>
<td><span class="math inline">\(E\)</span> launches per layer, idle GPU between them</td>
</tr>
<tr class="even">
<td>Capacity factor with token dropping</td>
<td>Static shapes, silently different outputs under load</td>
</tr>
<tr class="odd">
<td>Gate weights from bias-adjusted scores</td>
<td>Plausible but wrong outputs, no error</td>
</tr>
<tr class="even">
<td>Forgetting renormalization or <code>routed_scaling_factor</code></td>
<td>Output scaled wrongly by a per-token factor</td>
</tr>
<tr class="odd">
<td>Padding rows not masked on store</td>
<td>Writes past the output buffer, or over real rows</td>
</tr>
<tr class="even">
<td>Launching tiles for empty experts</td>
<td>Weight bytes read for nothing, which hurts most at decode</td>
</tr>
<tr class="odd">
<td>One tile config for all batch sizes</td>
<td>Prefill-tuned 64-row tiles at decode, or <code>mma.sync</code> tiles at prefill</td>
</tr>
<tr class="even">
<td>Benchmarking with uniform random routing</td>
<td>Hides hot-expert stragglers</td>
</tr>
</tbody>
</table>
</section>
<section id="checkpoint" class="level2">
<h2 class="anchored" data-anchor-id="checkpoint">Checkpoint</h2>
<ul>
<li>Explain why an MoE layer is <span class="math inline">\(E\)</span> ragged GEMMs whose sizes are only known on the device.</li>
<li>Write the <code>sorted_ids</code> / <code>expert_ids</code> contract and compute it with a histogram and a scan.</li>
<li>Describe how a fused kernel gathers A rows for GEMM1 versus GEMM2, and where the router weight is applied.</li>
<li>State the DeepSeek-V3 routing rule, and which scores the gate weights come from.</li>
<li>Use “FLOP per weight byte <span class="math inline">\(\approx 2n_e\)</span>” to say whether a given MoE layer is bandwidth- or compute-bound.</li>
<li>Explain why 16-row tiles cannot use Hopper <code>wgmma</code>, and name two ways decode kernels deal with small row counts.</li>
</ul>
</section>
<section id="try-this" class="level2">
<h2 class="anchored" data-anchor-id="try-this">Try this</h2>
<ol type="1">
<li>Change <code>moe_align.py</code> to compute <code>sorted_ids</code> without <code>argsort</code>: one pass for the histogram, an exclusive scan, and an atomic-style running counter per expert. Check it against the current output.</li>
<li>Add an <code>expert_map</code> argument for expert parallelism: experts not on this GPU get <code>expert_ids = -1</code>, and the kernel skips those tiles. Test with half the experts remote.</li>
<li>Fuse <code>silu(gate) * up</code> into the GEMM1 epilogue by computing the gate and up halves as two accumulators in the same program. Confirm the interpreter test still passes.</li>
<li>Run <code>compile_check.py</code> with <code>BLOCK_M ∈ {16, 32, 64, 128}</code> and record which tiles get <code>wgmma</code>, and the shared memory each needs.</li>
<li>On a GPU, capture real <code>topk_ids</code> from a small MoE model, then sweep <span class="math inline">\(T\in\{1, 8, 64, 512, 4096\}\)</span> and plot achieved GB/s and TFLOP/s for <code>BLOCK_M=16</code> and <code>BLOCK_M=64</code>.</li>
</ol>
</section>
<section id="summary" class="level2">
<h2 class="anchored" data-anchor-id="summary">Summary</h2>
<p>An MoE layer replaces one GEMM with many small, ragged, data-dependent GEMMs. Making it fast starts with metadata: a histogram, a scan, and a scatter turn the router’s <code>topk_ids</code> into a block-aligned table that maps every tile to one expert. A single grouped-GEMM launch then either reads a permuted copy of the activations or gathers rows through the table, and scatters results back to token order with the router weight folded in. Routing semantics are part of correctness, especially the selection-only bias in DeepSeek-style routers. Shape arithmetic tells you which regime you are in: decode streams weights at about 2 FLOP per byte and needs bandwidth-oriented kernels, while prefill reaches the ridge only when experts see hundreds of rows. Verify the indexing on a CPU with the Triton interpreter, compile ahead of time for the target, and benchmark with real routing traces.</p>
</section>
<section id="sources-for-further-reading" class="level2">
<h2 class="anchored" data-anchor-id="sources-for-further-reading">Sources (for further reading)</h2>
<ul>
<li>DeepSeek-AI, “DeepSeek-V3 Technical Report” (arXiv:2412.19437): auxiliary-loss-free balancing with a selection bias, sigmoid gating, node-limited routing. Model <code>config.json</code> files on Hugging Face for DeepSeek-V3, Kimi K2, Qwen3-235B-A22B, gpt-oss-120b, and Mixtral-8x7B (expert counts and routing fields).</li>
<li>vLLM source: <code>vllm/model_executor/layers/fused_moe/moe_align_block_size.py</code> (docstring example reproduced in section 5) and <code>fused_moe.py</code> (<code>fused_moe_kernel</code>, the per-token assignment heuristic, tuned configs).</li>
<li>PyTorch documentation: <code>torch.nn.functional.grouped_mm</code> (2.14); torchtitan MoE (<code>_run_experts_grouped_mm</code>).</li>
<li>Gale, Narayanan, Young, Zaharia, “MegaBlocks: Efficient Sparse Training with Mixture-of-Experts” (MLSys 2023, arXiv:2211.15841).</li>
<li>Fedus, Zoph, Shazeer, “Switch Transformers” (arXiv:2101.03961): capacity factor and token dropping.</li>
<li>DeepSeek-AI, DeepGEMM repository (m-grouped contiguous and masked FP8 GEMMs) and DeepEP repository (expert-parallel dispatch and combine kernels).</li>
<li>NVIDIA CUTLASS documentation: grouped GEMM. PTX ISA: <code>wgmma.mma_async</code> shapes (m64nNk16).</li>
<li>Triton documentation: tutorial “Group GEMM”, <code>TRITON_INTERPRET=1</code>, and <code>triton.compile</code> with <code>GPUTarget</code>.</li>
</ul>


</section>
</section>

</main> <!-- /main -->
<!-- reader-mode: reliable focus layout -->
<script>
// Reliable reader / focus mode for Quarto books.
// Quarto's stock toggle is easy to miss visually (opacity-only chrome) and its
// onclick can race with other handlers. We own the control fully:
//   body.quarto-reader-active  → layout CSS hides sidebars + widens article
(function () {
  const STORAGE_KEY = "quarto-reader-mode";
  const BODY_CLASS = "quarto-reader-active";
  const TOGGLE_CLASS = "reader";

  function isOn() {
    try {
      return window.localStorage.getItem(STORAGE_KEY) === "true";
    } catch (_) {
      return document.body.classList.contains(BODY_CLASS);
    }
  }

  function setOn(on) {
    on = !!on;
    try {
      window.localStorage.setItem(STORAGE_KEY, on ? "true" : "false");
    } catch (_) {
      /* private mode / file restrictions */
    }
    document.documentElement.classList.toggle(BODY_CLASS, on);
    document.body.classList.toggle(BODY_CLASS, on);
    document.querySelectorAll(".quarto-reader-toggle").forEach(function (el) {
      el.classList.toggle(TOGGLE_CLASS, on);
      el.setAttribute("aria-pressed", on ? "true" : "false");
    });
  }

  function toggle(ev) {
    if (ev) {
      ev.preventDefault();
      ev.stopPropagation();
      if (ev.stopImmediatePropagation) ev.stopImmediatePropagation();
    }
    setOn(!isOn());
    return false;
  }

  function wireToggles() {
    document.querySelectorAll(".quarto-reader-toggle").forEach(function (el) {
      // Always re-bind: Quarto may re-render nav tools
      el.onclick = null;
      el.removeAttribute("onclick");
      el.setAttribute("href", "#");
      el.setAttribute("role", "button");
      el.setAttribute("aria-pressed", isOn() ? "true" : "false");
      el.setAttribute("title", "Toggle reader mode (hide sidebars, wider text)");
      if (el.dataset.readerWired === "1") return;
      el.dataset.readerWired = "1";
      // Capture phase so we win over any leftover handlers
      el.addEventListener("click", toggle, true);
    });
  }

  function installGlobal() {
    // Replace Quarto's implementation entirely (layout CSS is ours)
    window.quartoToggleReader = function () {
      setOn(!isOn());
    };
  }

  function init() {
    installGlobal();
    wireToggles();
    setOn(isOn());

    // Quarto assigns window.quartoToggleReader late in DOMContentLoaded — reassert
    let n = 0;
    const id = window.setInterval(function () {
      installGlobal();
      wireToggles();
      if (++n > 40) window.clearInterval(id);
    }, 50);
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", init);
  } else {
    init();
  }
})();

</script>

<script>
/* topology-diagram-theme — monorepo dual-theme SVG swap
 * Spec: includes/diagrams/STANDARD.md
 * Light: diagram-<topic>.svg (PDF/EPUB + Quarto light)
 * Dark:  diagram-<topic>-dark.svg (Quarto dark HTML)
 * Markdown always embeds the light path; this rewrites <img src> on theme toggle.
 */
(function () {
  // Illustrated dual-theme only. Conceptual mono uses diagram-concept-* / diagram-mono-*
  // or known legacy mono stems (never swap those — no -dark sibling).
  const MONO_RE =
    /(?:^|\/)diagram-(?:concept|mono)-|diagram-(?:encapsulation|learning-path|network-planes|underlay-overlay|verify-loop)(?:-dark)?\.svg/i;

  function isDualDiagramName(name) {
    if (!name || !/^diagram-.+\.svg$/i.test(name)) return false;
    if (MONO_RE.test(name)) return false;
    return true;
  }

  function isDark() {
    return document.body.classList.contains("quarto-dark");
  }

  function desiredSrc(src, dark) {
    if (!src) return src;
    const name = (src.split("/").pop() || "").split("?")[0];
    if (!isDualDiagramName(name) && !isDualDiagramName(name.replace(/-dark\.svg$/i, ".svg"))) {
      return src;
    }
    // After stripping -dark, still must be dual
    const baseName = name.replace(/-dark\.svg$/i, ".svg");
    if (!isDualDiagramName(baseName) && !/^diagram-.+\.svg$/i.test(baseName)) return src;
    if (MONO_RE.test(baseName)) return src;

    if (dark) {
      return src.includes("-dark.svg")
        ? src
        : src.replace(/\.svg(\?.*)?$/i, "-dark.svg$1");
    }
    return src.replace(/-dark\.svg(\?.*)?$/i, ".svg$1");
  }

  function apply() {
    const dark = isDark();
    document.querySelectorAll("img").forEach(function (img) {
      const cur = img.getAttribute("src") || "";
      const next = desiredSrc(cur, dark);
      if (next && next !== cur) img.setAttribute("src", next);
    });
  }

  function observe() {
    apply();
    const obs = new MutationObserver(function () {
      apply();
    });
    obs.observe(document.body, { attributes: true, attributeFilter: ["class"] });
    document.addEventListener(
      "click",
      function (ev) {
        const t = ev.target;
        if (t && t.closest && t.closest(".quarto-color-scheme-toggle")) {
          window.setTimeout(apply, 0);
          window.setTimeout(apply, 50);
          window.setTimeout(apply, 200);
        }
      },
      true
    );
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", observe);
  } else {
    observe();
  }
})();
</script>
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'alternate';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } else {
    toggleColorMode(false);
  }
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../content/04-modern-frontier/08-flash-decoding-split-kv.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-title">Flash-Decoding: Split-KV Attention for Long-Context Decode</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../content/05-ai-written-kernels/01-deepseek-flashmla-and-deepgemm.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-title">DeepSeek: FlashMLA &amp; DeepGEMM</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>